# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# The unpack logic in this file (_materialize_deb_data_into_root, _unpack) is
# adapted from `apt/private/sysroot_repository.bzl` in
# https://github.com/LittleHuba/rules_distroless (commit
# e1df344fde5adaef7397c34076b56f27771d08b8), which is licensed under the
# Apache License, Version 2.0 (https://github.com/LittleHuba/rules_distroless
# has no per-file copyright headers; the repository's LICENSE file is
# Apache-2.0). It has been reworked to consume a plain rules_distroless
# `apt.install()` lockfile (as produced by the upstream, BCR-published
# rules_distroless, without requiring that fork's fork-only `apt.sysroot()`
# extension or its `dependency_set`-keyed lockfile format), so this repo needs
# no `rules_distroless` override.

"""Repository rule that unpacks a rules_distroless apt.install() lockfile's
packages into a flat, fetch-time sysroot directory, for use as a C/C++
toolchain sysroot (e.g. toolchains_llvm's `llvm.sysroot(label = ...)`)."""

_BUILD_TMPL = """\
"Generated by sysroot_from_lock. DO NOT EDIT."

filegroup(
    name = "sysroot",
    srcs = ["."],
    visibility = ["//visibility:public"],
)
"""

def _materialize_deb_data_into_root(rctx, deb_path, ar_dir, unpack_dir):
    """Unpacks the data.tar.* payload of a .deb archive into unpack_dir.

    This relies exclusively on Bazel's built-in support for extracting the
    `ar` container format used by .deb files, and the nested `tar.*` payload,
    via repository_ctx.extract().
    """

    # .deb files are `ar` archives containing debian-binary, control.tar.* and
    # data.tar.* members. Extracting unpacks those members as plain,
    # uncompressed files (the ".deb" extension is auto-detected as ar).
    rctx.extract(archive = deb_path, output = ar_dir)

    data_member = None
    for entry in rctx.path(ar_dir).readdir():
        if entry.basename.startswith("data.tar"):
            data_member = entry
            break

    if data_member == None:
        fail("No data archive found in {}".format(deb_path))

    # The archive type (tar.gz/tar.xz/tar.zst/...) is auto-detected from the
    # data_member's file extension.
    rctx.extract(archive = data_member, output = unpack_dir)

def _unpack(rctx, packages, architecture):
    unpack_dir = "sysroot"
    work_dir = ".unpack_work"

    for package in packages:
        if package["arch"] not in (architecture, "all"):
            continue

        key = package["key"]
        deb_path = "{}/{}.deb".format(work_dir, key)
        ar_dir = "{}/{}.ar".format(work_dir, key)

        rctx.download(
            output = deb_path,
            sha256 = package["sha256"],
            url = package["urls"],
        )

        _materialize_deb_data_into_root(rctx, deb_path, ar_dir, unpack_dir)

    rctx.delete(work_dir)

def _sysroot_from_lock_impl(rctx):
    lock = json.decode(rctx.read(rctx.attr.lock))
    if lock["version"] != 1:
        fail("invalid lockfile version")

    _unpack(rctx, lock["packages"], rctx.attr.architecture)

    rctx.file("sysroot/BUILD.bazel", _BUILD_TMPL)

sysroot_from_lock = repository_rule(
    implementation = _sysroot_from_lock_impl,
    attrs = {
        "lock": attr.label(
            mandatory = True,
            doc = "Label of a rules_distroless apt.install() lockfile's " +
                  "generated lock.json file, e.g. " +
                  "'@<name>_resolve//:lock.json'.",
        ),
        "architecture": attr.string(
            mandatory = True,
            doc = "Debian architecture (e.g. 'amd64') to unpack packages " +
                  "for; packages for other architectures in the lockfile " +
                  "are skipped. Packages with arch 'all' are always " +
                  "included.",
        ),
    },
    doc = "Unpacks a rules_distroless apt.install() lockfile's packages " +
          "for a single architecture into a flat, fetch-time sysroot " +
          "directory, exposed as a `:sysroot` filegroup.",
)
