# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""Update runner: refresh test_case_coverage.lock.yaml from current gtest.lobster output.

Environment variables
---------------------
TEST_CASE_COVERAGE_LOBSTER_MANIFEST
    Path to a newline-delimited file listing lobster-req-trace JSON paths
    (one per line).  Requirement IDs are extracted from these files.
TEST_CASE_COVERAGE_GTEST_LOBSTER
    Path to the gtest.lobster file produced by subrule_lobster_gtest.
TEST_CASE_COVERAGE_LOCK_FILE_WORKSPACE_PATH
    Workspace-relative path of the committed lock YAML file to overwrite.
    Distinct from ``TEST_CASE_COVERAGE_LOCK_FILE`` (used by test_runner),
    which points to a resolvable file rather than a workspace-relative one.
TEST_CASE_COVERAGE_LABEL
    Bazel label of the test_case_coverage target (used in log output only).
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

from test_case_coverage.check_lock import validate_specs
from test_case_coverage.compute_lock import serialize
from test_case_coverage.read_gtest_lobster import resolve_path
from test_case_coverage.runner_common import require_env, scan_and_compute

logger = logging.getLogger(__name__)


def main(argv: list[str] | None = None) -> None:
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s", force=True)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--allow-check-failures",
        action="store_true",
        help="Write the lock file even when GWT spec validation fails (mirrors test_runner's flag of the same name).",
    )
    args = parser.parse_args(argv)

    lobster_manifest = resolve_path(require_env("TEST_CASE_COVERAGE_LOBSTER_MANIFEST"))
    gtest_lobster_path = resolve_path(require_env("TEST_CASE_COVERAGE_GTEST_LOBSTER"))
    # The lock file must be resolved to the source tree so that ``bazel run``
    # overwrites the committed file.  ``$BUILD_WORKSPACE_DIRECTORY`` is set
    # by Bazel for all ``bazel run`` invocations; the env var carries the
    # package-relative path (e.g. ``score/message_passing/test_case_coverage.lock.yaml``).
    _raw_lock = require_env("TEST_CASE_COVERAGE_LOCK_FILE_WORKSPACE_PATH")
    build_workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if build_workspace:
        lock_file_path = Path(build_workspace) / _raw_lock
    else:
        lock_file_path = resolve_path(_raw_lock)
    label = os.environ.get("TEST_CASE_COVERAGE_LABEL", "<unknown>")
    package = os.environ.get("TEST_CASE_COVERAGE_PACKAGE", "")

    # Steps 1-3: extract requirement metadata, scan gtest.lobster, compute lock
    req_metadata, lock = scan_and_compute(lobster_manifest, gtest_lobster_path, package=package, label=label)
    if not req_metadata:
        logger.warning("[%s] No CompReq requirement IDs found in lobster manifest.", label)

    # Step 3b: validate GWT specs -- same severity as test_runner (ERROR + exit)
    # so `.update` cannot silently write a lock file that the check step
    # (test_runner) would then reject for missing specs. --allow-check-failures
    # writes the lock anyway, mirroring test_runner's flag of the same name.
    spec_ok, spec_issues = validate_specs(lock)
    if not spec_ok:
        logger.error("One or more test cases are missing GWT spec annotations:")
        for line in spec_issues:
            logger.error(line)
        if not args.allow_check_failures:
            logger.error(
                "Lock file NOT written. Add RecordProperty given/when/then "
                "annotations, or pass --allow-check-failures to write anyway."
            )
            sys.exit(1)

    # Step 4: write lock file
    yaml_content = serialize(lock)
    # `label` is TEST_CASE_COVERAGE_LABEL, which is already this `.update`
    # target's own label (see component.bzl's _component_update_impl) — do
    # not append another ".update" suffix here, or the generated
    # instructions end up as "<component>.update.update".
    header = (
        f"# test_case_coverage.lock.yaml — auto-generated by test_case_coverage\n"
        f"# Run `bazel run {label}` to refresh.\n"
    )
    lock_file_path.write_text(header + yaml_content, encoding="utf-8")

    logger.info("[%s] Lock file updated: %s", label, lock_file_path)
    for req in lock.requirements:
        logger.info("  %s: %d test case(s)", req.id, len(req.test_cases))


if __name__ == "__main__":
    main()
