# This file is at the root level, as it applies to all Python code,
# not only to docs or to tools.
[tool.pyright]
extends = "python_basics/pyproject.toml"

exclude = [
    "**/__pycache__",
    "**/.*",
    "**/bazel-*",
]

[tool.ruff]
extend = "python_basics/pyproject.toml"

extend-exclude = [
    "**/__pycache__",
    "/.*",
    "bazel-*",
]
