# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
from typing import List, Optional, Set
import unittest
from pathlib import Path

from test_runner import TestRunner


class BasicTracingTest(unittest.TestCase):
    """Tests for basic tracing tag extraction from source files."""

    def setUp(self):
        cwd = Path(__file__).parent
        # Resolve lobster_bazel binary from runfiles
        tool_path = Path(__file__).parent.parent / "lobster-bazel"
        self._test_runner = TestRunner(cwd, tool_path)
        self._data_directory: Path = cwd / "data"

        self._test_runner.copy_file_to_working_directory(
            self._data_directory / "source_with_tags.py"
        )
        self._test_runner.copy_file_to_working_directory(
            self._data_directory / "file_list.txt"
        )

    def _configure_cmd_args(
        self,
        output_file: str,
        namespace: Optional[str] = None,
        inputs: List[str] = ["file_list.txt"],
    ):
        output_file_path: Path = self._test_runner.working_dir / output_file

        self._test_runner.cmd_args.output = output_file_path.as_posix()
        self._test_runner.cmd_args.tags = ["req-traceability"]
        self._test_runner.cmd_args.inputs = inputs

        if namespace:
            self._test_runner.cmd_args.namespace = namespace

        return output_file_path

    # gToDo: delete this helper function
    def load_output_file(self, output_file: Path):
        """Declares an output file that should be generated by the tool."""
        print(f"Declaring output file: {output_file}")
        with open(output_file, "r") as f:
            content = f.read()
        return content

    def test_python_file_with_tracing_tags(self):
        """
        Test that tracing tags are correctly extracted from a Python source file.
        """

        output_file_path = self._configure_cmd_args(
            output_file="source_with_tags.lobster"
        )

        completed_process = self._test_runner.run_tool_test()

        self.assertEqual(completed_process.returncode, 0)

        missing: Set[str] = self._test_runner.verify_lobster_tags(
            output_file_path,
            ["source COMP_REQ_001", "source FEAT_REQ_042", "source FEAT_REQ_043"],
        )

        self.assertFalse(missing, f"Missing tags in output: {missing}")

    def test_custom_namespace(self):
        """
        Test that the custom namespace is applied to extracted tracing tags.
        """

        output_file_path = self._configure_cmd_args(
            output_file="source_ns.lobster", namespace="impl"
        )

        completed_process = self._test_runner.run_tool_test()

        self.assertEqual(completed_process.returncode, 0)

        missing: Set[str] = self._test_runner.verify_lobster_tags(
            output_file_path,
            ["impl COMP_REQ_001", "impl FEAT_REQ_042", "impl FEAT_REQ_043"],
        )

        self.assertFalse(missing, f"Missing tags in output: {missing}")

    def test_no_file_list_inputs(self):
        """
        Test that an empty output is produced when no file-list inputs are given.
        """
        out_file_path = self._configure_cmd_args(
            output_file="empty.lobster",
            inputs=[],  # No file list inputs
        )

        completed_process = self._test_runner.run_tool_test()

        self.assertEqual(completed_process.returncode, 0)
        self.assertEqual(
            completed_process.stdout,
            f"lobster-bazel: wrote 0 items to {out_file_path}\n",
        )


if __name__ == "__main__":
    unittest.main()
