requirements "Use Cases" {
  source: "use_cases_lobster.lobster";
}

requirements "Potential Errors" {
  source: "potential_errors_lobster.lobster";
  trace to: "Use Cases";
}

requirements "Tool Requirements" {
  source: "tool_requirements_lobster.lobster";
  trace to: "Potential Errors";
}

implementation "Code" {
  source: "rules_score_impl.lobster";
  trace to: "Tool Requirements";
}
