"""Rule to expose SBOM metadata collected by the module extension.

This rule wraps the metadata JSON file generated by the module extension
and makes it available for the SBOM generation action.
"""

load(":providers.bzl", "SbomMetadataInfo")

def _sbom_metadata_rule_impl(ctx):
    """Implementation of sbom_metadata_rule.

    The metadata is passed as a JSON file to the SBOM generator action,
    rather than being parsed at analysis time.

    Args:
        ctx: The rule context

    Returns:
        A list of providers including SbomMetadataInfo with file reference
    """
    metadata_file = ctx.file.metadata_json

    # We can't read files at analysis time in Bazel rules, so we pass
    # the file reference and let the generator read it at execution time.
    # The SbomMetadataInfo provider carries empty dicts here - the actual
    # metadata is read by the Python generator from the JSON file.
    return [
        DefaultInfo(files = depset([metadata_file])),
        SbomMetadataInfo(
            modules = {},
            crates = {},
            http_archives = {},
        ),
        # Also provide the file itself for the rule to use
        OutputGroupInfo(metadata_file = depset([metadata_file])),
    ]

sbom_metadata_rule = rule(
    implementation = _sbom_metadata_rule_impl,
    attrs = {
        "metadata_json": attr.label(
            mandatory = True,
            allow_single_file = [".json"],
            doc = "JSON file containing SBOM metadata",
        ),
    },
    provides = [SbomMetadataInfo],
    doc = "Exposes SBOM metadata collected by the module extension",
)
