# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""
Dependability Analysis build rules for S-CORE projects.

A dependability analysis aggregates sub-analysis rules

  * **safety_analysis**   – ``safety_analysis`` rule targets (failure modes, safety measures,
                            and optional root cause FTA diagrams).
  * **security_analysis** – security analysis rule targets (placeholder,
                            optional).

It also validates root-cause-coverage completeness: every ``RootCause``
generated by any ``safety_analysis`` sub-target's ``root_causes`` FTA diagrams must be
addressed by at least one Mitigation, AoU, or CompReq -- combining each
``safety_analysis`` sub-target's own safety measures with this rule's own ``measures``
attribute, via a coverage-check-only invocation of ``safety_analysis_assembler``.
"""

load("@lobster//:lobster.bzl", "subrule_lobster_html_report", "subrule_lobster_report")
load("//bazel/rules/rules_score:providers.bzl", "AnalysisInfo", "ArchitecturalDesignInfo", "DependabilityAnalysisInfo", "SafetyAnalysisProviderInfo", "SphinxSourcesInfo")
load("//bazel/rules/rules_score/private:lobster_config.bzl", "format_lobster_sources")
load("//bazel/rules/rules_score/private:verbosity.bzl", "VERBOSITY_ATTR", "get_log_level")

# ============================================================================
# Private Helpers
# ============================================================================

def _collect_analysis_providers(sa, rst_srcs_list, rst_deps_list, rst_aux_list, lobster_files):
    """Collect analysis providers from a single sub-analysis target.

    Updates the provided lists/dicts in-place.

    Args:
        sa:            A sub-analysis target (safety_analysis or security).
        rst_srcs_list: List of depsets to extend with SphinxSourcesInfo.srcs.
        rst_deps_list: List of depsets to extend with SphinxSourcesInfo.deps.
        rst_aux_list:  List of depsets to extend with SphinxSourcesInfo.aux_srcs.
        lobster_files: Dict to update with AnalysisInfo.lobster_files
                       (canonical name → File).
    """
    if SphinxSourcesInfo in sa:
        rst_srcs_list.append(sa[SphinxSourcesInfo].srcs)
        rst_deps_list.append(sa[SphinxSourcesInfo].deps)
        if sa[SphinxSourcesInfo].aux_srcs:
            rst_aux_list.append(sa[SphinxSourcesInfo].aux_srcs)
    if AnalysisInfo in sa:
        lobster_files.update(sa[AnalysisInfo].lobster_files)

# ============================================================================
# Private Rule Implementation
# ============================================================================

def _dependability_analysis_impl(ctx):
    """Implementation for dependability_analysis rule.

    Collects artefacts from all sub-analysis targets, generates the
    combined lobster traceability config and report, and creates a
    lobster-ci-report test executable.

    Args:
        ctx: Rule context.

    Returns:
        List of providers: DefaultInfo, DependabilityAnalysisInfo,
        SphinxSourcesInfo.
    """
    dfa_rst_files = depset(ctx.files.dfa)

    arch_design_info = None
    if ctx.attr.arch_design and ArchitecturalDesignInfo in ctx.attr.arch_design:
        arch_design_info = ctx.attr.arch_design[ArchitecturalDesignInfo]

    rst_srcs_transitive = [dfa_rst_files]
    rst_deps_transitive = [dfa_rst_files]
    rst_aux_transitive = []
    lobster_files = {}  # canonical name → File, merged from all sub-analyses

    # -------------------------------------------------------------------------
    # Collect from safety_analysis targets
    # -------------------------------------------------------------------------
    safety_analysis_output_files = []
    fta_events_transitive = []
    safetymeasures_transitive = [depset(ctx.files.measures)]
    dep_files_transitive = []
    for sa in ctx.attr.safety_analysis:
        safety_analysis_output_files.append(sa[DefaultInfo].files)
        _collect_analysis_providers(sa, rst_srcs_transitive, rst_deps_transitive, rst_aux_transitive, lobster_files)
        if SafetyAnalysisProviderInfo in sa:
            trlc = sa[SafetyAnalysisProviderInfo]
            fta_events_transitive.append(trlc.fta_events)
            safetymeasures_transitive.append(trlc.safetymeasures)
            dep_files_transitive.append(trlc.failuremodes)
            dep_files_transitive.append(trlc.spec)

    # -------------------------------------------------------------------------
    # Collect from security_analysis targets
    # -------------------------------------------------------------------------
    security_output_files = []
    for sa in ctx.attr.security_analysis:
        security_output_files.append(sa[DefaultInfo].files)
        _collect_analysis_providers(sa, rst_srcs_transitive, rst_deps_transitive, rst_aux_transitive, lobster_files)

    # arch_design files are handled separately by dependable_element via its
    # architectural_design attribute, so they are not included in this rule's
    # sphinx deps to avoid orphan warnings.

    all_rst_srcs = depset(transitive = rst_srcs_transitive)
    all_rst_deps = depset(transitive = rst_deps_transitive)
    all_rst_aux = depset(transitive = rst_aux_transitive) if rst_aux_transitive else depset()

    # =========================================================================
    # Lobster traceability report (combined FM + CM + FTA)
    # =========================================================================
    lobster_report_file = None
    lobster_html_file = None
    report_files = []

    all_lobster_file_objects = lobster_files.values()
    arch_lobster_files = arch_design_info.public_api_lobster_files.to_list() if arch_design_info else []
    all_lobster_file_objects = list(all_lobster_file_objects) + arch_lobster_files
    if all_lobster_file_objects:
        lobster_config = ctx.actions.declare_file(
            "{}/traceability_config".format(ctx.label.name),
        )

        ctx.actions.expand_template(
            template = ctx.file._lobster_sa_template,
            output = lobster_config,
            substitutions = {
                "{ARCH_SOURCES}": format_lobster_sources(arch_lobster_files),
                "{FM_SOURCES}": format_lobster_sources([lobster_files["failuremodes.lobster"]] if "failuremodes.lobster" in lobster_files else []),
                "{SAFETYMEASURES_SOURCES}": format_lobster_sources([lobster_files["safetymeasures.lobster"]] if "safetymeasures.lobster" in lobster_files else []),
                "{FTA_FM_SOURCES}": format_lobster_sources([lobster_files["fta_failure_modes.lobster"]] if "fta_failure_modes.lobster" in lobster_files else []),
                "{RC_SOURCES}": format_lobster_sources([lobster_files["fta_root_causes.lobster"]] if "fta_root_causes.lobster" in lobster_files else []),
            },
        )

        lobster_report_file = subrule_lobster_report(all_lobster_file_objects, lobster_config)
        lobster_html_file = subrule_lobster_html_report(lobster_report_file)

        if lobster_report_file:
            report_files.append(lobster_report_file)
        if lobster_html_file:
            report_files.append(lobster_html_file)

    # =========================================================================
    # Root-cause coverage completeness check (combined across safety_analysis targets)
    # =========================================================================
    # Every RootCause generated by any safety_analysis sub-target's root_causes FTA
    # diagrams must be addressed by at least one Mitigation, AoU, or CompReq --
    # possibly one declared via this dependability_analysis's own `measures`
    # attribute rather than scoped to a single safety_analysis target.
    fta_events_files = depset(transitive = fta_events_transitive).to_list()
    uncovered_root_causes = None
    if fta_events_files:
        uncovered_root_causes = ctx.actions.declare_file(
            "{}/uncovered_root_causes.json".format(ctx.label.name),
        )
        safetymeasures_files = depset(transitive = safetymeasures_transitive).to_list()
        dep_files = depset(transitive = dep_files_transitive).to_list()

        args = ctx.actions.args()
        args.add("--uncovered-root-causes-output", uncovered_root_causes.path)
        args.add("--fta-events")
        args.add_all(fta_events_files)
        if safetymeasures_files:
            args.add("--measures")
            args.add_all(safetymeasures_files)
        if dep_files:
            args.add("--dep-files")
            args.add_all(dep_files)
        args.add("--log-level", get_log_level(ctx))
        ctx.actions.run(
            inputs = fta_events_files + safetymeasures_files + dep_files,
            outputs = [uncovered_root_causes],
            executable = ctx.executable._safety_analysis_assembler,
            arguments = [args],
            progress_message = "Checking root-cause coverage for %s" % ctx.label.name,
        )
        report_files.append(uncovered_root_causes)

    # =========================================================================
    # Test executable (lobster-ci-report + root-cause coverage)
    # =========================================================================
    test_executable = ctx.actions.declare_file(
        "{}_lobster_ci_test_executable".format(ctx.attr.name),
    )

    commands = []
    runfiles_files = []
    if lobster_report_file:
        if ctx.attr.maturity == "development":
            # Development mode: report traceability issues without failing the
            # build, matching the maturity pattern used by dependable_element.
            commands.append("{ci} {report} || echo 'WARNING: lobster traceability check failed (maturity=development)'".format(
                ci = ctx.executable._lobster_ci_report.short_path,
                report = lobster_report_file.short_path,
            ))
        else:
            commands.append("{ci} {report}".format(
                ci = ctx.executable._lobster_ci_report.short_path,
                report = lobster_report_file.short_path,
            ))
        runfiles_files.extend([ctx.executable._lobster_ci_report, lobster_report_file])

    if uncovered_root_causes:
        # `python3` is available on the exec host but not declared as a Bazel
        # dependency here (matches the pattern of other inline shell/python
        # glue in this rule); the check is intentionally tiny.
        check = """python3 - "{path}" "{maturity}" <<'PYEOF'
import json, sys
path, maturity = sys.argv[1], sys.argv[2]
data = json.load(open(path))
if data:
    msg = "root causes not addressed by any Mitigation/AoU/CompReq: " + ", ".join(data)
    if maturity == "development":
        print("WARNING: " + msg, file=sys.stderr)
    else:
        print("ERROR: " + msg, file=sys.stderr)
        sys.exit(1)
PYEOF""".format(path = uncovered_root_causes.short_path, maturity = ctx.attr.maturity)
        commands.append(check)
        runfiles_files.append(uncovered_root_causes)

    if commands:
        script = "#!/bin/bash\nset -o pipefail\n" + "\n".join(commands) + "\n"
        ctx.actions.write(output = test_executable, content = script, is_executable = True)
    else:
        ctx.actions.write(output = test_executable, content = "#!/bin/sh\nexit 0\n", is_executable = True)

    runfiles = ctx.runfiles(files = runfiles_files)
    if lobster_report_file:
        runfiles = runfiles.merge(ctx.attr._lobster_ci_report[DefaultInfo].default_runfiles)

    # =========================================================================
    # Build providers
    # =========================================================================
    all_output_files = depset(
        report_files,
        transitive = [dfa_rst_files] + safety_analysis_output_files + security_output_files,
    )

    return [
        DefaultInfo(
            runfiles = runfiles,
            files = all_output_files,
            executable = test_executable,
        ),
        DependabilityAnalysisInfo(
            safety_analysis = depset(transitive = safety_analysis_output_files),
            security_analysis = depset(transitive = security_output_files),
            dfa = dfa_rst_files,
            arch_design = arch_design_info,
            name = ctx.label.name,
            lobster_files = lobster_files,
        ),
        SphinxSourcesInfo(
            srcs = all_rst_srcs,
            deps = all_rst_deps,
            aux_srcs = all_rst_aux,
        ),
    ]

# ============================================================================
# Rule Definition
# ============================================================================

_dependability_analysis_test = rule(
    implementation = _dependability_analysis_impl,
    doc = "Aggregates dependability analysis sub-analyses (safety_analysis, security_analysis) " +
          "and validates the combined traceability chain via lobster-ci-report, plus " +
          "root-cause-coverage completeness (every RootCause addressed by a Mitigation, " +
          "AoU, or CompReq) across every safety_analysis sub-target.",
    attrs = dict(
        {
            "safety_analysis": attr.label_list(
                providers = [AnalysisInfo],
                mandatory = False,
                doc = "safety_analysis rule targets (failure modes + safety measures).",
            ),
            "security_analysis": attr.label_list(
                providers = [AnalysisInfo],
                mandatory = False,
                doc = "Security analysis rule targets (placeholder -- not yet implemented).",
            ),
            "dfa": attr.label_list(
                allow_files = [".rst", ".md"],
                mandatory = False,
                doc = "Dependent Failure Analysis (DFA) documentation (placeholder).",
            ),
            "arch_design": attr.label(
                providers = [ArchitecturalDesignInfo],
                mandatory = False,
                doc = "Reference to architectural_design target for interface tracing.",
            ),
            "measures": attr.label_list(
                allow_files = [".trlc"],
                mandatory = False,
                doc = "Additional Mitigation/AoU/CompReq .trlc files not scoped to a single " +
                      "safety_analysis target, considered for the root-cause-coverage completeness check.",
            ),
            "maturity": attr.string(
                default = "release",
                values = ["release", "development"],
                doc = "Maturity level of the dependability analysis. 'release' (default) fails `bazel test` when traceability links are missing; 'development' emits a warning and continues.",
            ),
            "_lobster_ci_report": attr.label(
                default = "@lobster//:lobster-ci-report",
                executable = True,
                cfg = "exec",
                doc = "lobster-ci-report executable for test execution.",
            ),
            "_lobster_sa_template": attr.label(
                default = Label("//bazel/rules/rules_score/lobster/config:lobster_sa_template"),
                allow_single_file = True,
                doc = "Lobster config template for safety analysis traceability.",
            ),
            "_safety_analysis_assembler": attr.label(
                default = Label("//bazel/rules/rules_score:safety_analysis_assembler"),
                executable = True,
                allow_files = True,
                cfg = "exec",
                doc = "Safety-analysis page assembler, invoked in coverage-check-only mode " +
                      "(no --output/--template) to compute uncovered_root_causes.json.",
            ),
        },
        **VERBOSITY_ATTR
    ),
    subrules = [subrule_lobster_report, subrule_lobster_html_report],
    test = True,
)

# ============================================================================
# Public Macro
# ============================================================================

def dependability_analysis(
        name,
        safety_analysis = [],
        security_analysis = [],
        dfa = [],
        arch_design = None,
        measures = [],
        maturity = "release",
        **kwargs):
    """Define dependability analysis following S-CORE process guidelines.

    Aggregates up to three sub-analysis rules and validates the combined
    traceability chain (FM + Safety Measures + FTA) via ``lobster-ci-report``, and
    checks root-cause-coverage completeness: every ``RootCause`` generated by
    any ``safety_analysis`` sub-target's ``root_causes`` FTA diagrams must be addressed by
    at least one Mitigation, AoU, or CompReq -- including ones declared via
    ``measures`` rather than scoped to a single ``safety_analysis`` target.

    The target is a Bazel **test rule**.  During ``bazel build`` it produces
    aggregated documentation artefacts and the lobster traceability report.
    During ``bazel test`` it runs ``lobster-ci-report`` and the root-cause
    coverage check to validate the chain.

    Args:
        name: The name of the dependability analysis target.
        safety_analysis: Optional list of ``safety_analysis`` rule target labels.
        security_analysis: Optional list of security analysis rule target
            labels (placeholder -- not yet implemented).
        dfa: Optional list of ``.rst``/``.md`` DFA documentation files
            (placeholder).
        arch_design: Optional label to an ``architectural_design`` target
            (placeholder).
        measures: Optional list of additional Mitigation/AoU/CompReq ``.trlc``
            files not scoped to a single ``safety_analysis`` target, considered for the
            root-cause-coverage completeness check.
        maturity: 'release' (default) fails ``bazel test`` when traceability
            links are missing; 'development' emits a warning and continues.
        visibility: Bazel visibility.
        tags: Additional Bazel tags.

    Example:
        .. code-block:: starlark

            dependability_analysis(
                name = "my_da",
                safety_analysis = [":my_safety_analysis"],
            )
    """
    _dependability_analysis_test(
        name = name,
        safety_analysis = safety_analysis,
        security_analysis = security_analysis,
        dfa = dfa,
        arch_design = arch_design,
        measures = measures,
        maturity = maturity,
        **kwargs
    )
