# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""
Sphinx configuration template for SCORE modules using the shared S-CORE layout.

This mirrors the generic conf.template.py but swaps the stock Read-the-Docs
theme for the shared ``score_layout`` extension (from score_docs_as_code), so
the rendered site matches the baselibs / lifecycle documentation (top
navigation bar instead of the RTD expandable left sidebar).

This file is auto-generated from a template and should not be edited directly.
Template variables like {PROJECT_NAME} are replaced during Bazel build.
"""

import json
import os
import sys

from sphinx.util import logging

import sphinx_conf_helpers

# Create a logger with the Sphinx namespace
logger = logging.getLogger(__name__)


logger.debug("#" * 80)
logger.debug("# READING CONF.PY")
logger.debug("SYSPATH:" + str(sys.path))
logger.debug("EMV:" + str(os.environ))

for k, v in os.environ.items():
    logger.debug(str(k) + ": " + v)
# Project configuration - {PROJECT_NAME} will be replaced by the module name during build
project = "{PROJECT_NAME}"
author = "S-CORE"
version = "1.0"
release = "1.0.0"
project_url = "https://github.com/eclipse-score"  # Required by score_metamodel extension

# Enable the score_layout built-in version switcher (the same navbar dropdown
# used by the baselibs / lifecycle sites) instead of a custom flyout. When
# github_user / github_repo are set (i.e. not "dummy"), score_layout adds a
# "version-switcher" to the navbar pointing at
# https://<github_user>.github.io/<github_repo>/versions.json. This repo's docs
# are published at https://eclipse-score.github.io/tooling/, so the switcher
# reads https://eclipse-score.github.io/tooling/versions.json (generated by the
# deploy workflow).
html_context = {
    "github_user": "eclipse-score",
    "github_repo": "tooling",
    "github_version": "main",
    "doc_path": "bazel/rules/rules_score/docs",
}

# Remove the "Show Source" link from every page (pydata renders it in the
# secondary "On this page" sidebar unless source links are disabled).
html_show_sourcelink = False

# Sphinx extensions - comprehensive list for SCORE modules.
# score_layout (from score_docs_as_code) provides the shared S-CORE theme and
# top navigation used by the baselibs / lifecycle documentation sites. It is
# imported via its full package path because this repository's Sphinx binary
# puts the score_docs_as_code repo root (not src/extensions/) on sys.path.
extensions = [
    "sphinx_module_ext",
    "sphinx_needs",
    "sphinx_design",
    "myst_parser",
    "sphinxcontrib.plantuml",
    "trlc",
    "clickable_plantuml",
    "sphinx.ext.graphviz",
    "src.extensions.score_layout",
]

# MyST parser extensions
myst_enable_extensions = sphinx_conf_helpers.DEFAULT_MYST_ENABLE_EXTENSIONS

# Exclude patterns for Bazel builds. Design-fragment subdirectories (e.g.
# units/unit_1_design/) are included via '.. include::' directives and must
# not be treated as standalone pages -- see DEFAULT_EXCLUDE_PATTERNS.
exclude_patterns = sphinx_conf_helpers.DEFAULT_EXCLUDE_PATTERNS

# Suppress toctree warnings for documents absent from the needs builder's source
# tree.  The needs builder runs against only the static docs/ checkout; generated
# files (trlc_rst outputs, renamed_srcs, docs_library_deps) live in bazel-out/
# and are invisible to it.  Their toctree references produce toc.not_readable
# warnings that are cosmetic: the needs builder (sphinx-needs NeedsBuilder)
# captures only `.. need::` directives, not trlc `.. requirement:definition::`
# directives, so needs.json content is unaffected by missing files.
# This suppression is safe for the HTML phase because that phase relocates every
# file into a unified staging directory, so it never encounters toc.not_readable.
suppress_warnings = sphinx_conf_helpers.DEFAULT_SUPPRESS_WARNINGS

# Enable markdown rendering
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# Enable numref for cross-references
numfig = True

# sphinx-needs configuration loaded from the upstream S-CORE metamodel.
# The needs types, extra options, extra links and ID regex are derived
# from score_docs_as_code//src/extensions/score_metamodel:metamodel.yaml
# so they stay in sync with the upstream process description.
#
# Note: score_metamodel is NOT loaded as a Sphinx extension
# (i.e. extensions = [..., "score_metamodel"]) for the following reason:
# When loaded as an extension, score_metamodel registers a build-finished hook
# that runs needs validation via its checks/ modules (mandatory options,
# prohibited words, link pattern checks, etc.). Those check modules do
# bare "from score_metamodel import ..." imports, which require src/extensions/
# to be on sys.path. That path is only set up by aspect_rules_py's venv
# mechanism, not by the rules_python setup used here.
# Instead, sphinx_conf_helpers calls load_metamodel_data() directly from
# yaml_parser — the score_docs_as_code+ repo root IS on sys.path, so the
# import resolves — and we get only the type/option/regex data without
# activating the validation hooks.
_needs_schema = sphinx_conf_helpers.load_metamodel_needs_schema()
needs_types = _needs_schema["needs_types"]
needs_extra_options = _needs_schema["needs_extra_options"]
needs_extra_links = _needs_schema["needs_extra_links"]
needs_id_regex = _needs_schema["needs_id_regex"]


# ---------------------------------------------------------------------------
# Hermetic PlantUML / Graphviz / FTA metamodel tool resolution
# ---------------------------------------------------------------------------
# PLANTUML_BIN, GRAPHVIZ_DOT and FTA_METAMODEL_DIR are injected by the
# sphinx_module Bazel rule via the action env (see _hermetic_tool_env() in
# sphinx_module.bzl). Resolution (path rationale, hermeticity requirements,
# the FTA include-path JVM flag, etc.) is centralised in sphinx_conf_helpers
# so every conf.py -- this default template and any custom conf_template --
# shares one implementation. See docs/tooling_architecture.rst
# §"Hermetic tool path resolution".
graphviz_dot = sphinx_conf_helpers.resolve_graphviz_dot()
graphviz_output_format = "svg"

plantuml_output_format = "svg_obj"
# Reuses the graphviz_dot already resolved above instead of re-resolving
# GRAPHVIZ_DOT a second time.
plantuml = sphinx_conf_helpers.resolve_plantuml_command(graphviz_dot_path=graphviz_dot)

# HTML theme is provided by the score_layout extension (shared S-CORE theme);
# do not set html_theme here.

logger.debug("#" * 80)


# ---------------------------------------------------------------------------
# Home-page section styling
# ---------------------------------------------------------------------------
# The landing page (index.rst) lists the four documentation sections
# (Usage / Validation / Development / Tool Qualification) through a single
# top-level toctree so the pydata top navbar shows exactly those four entries.
# In the page body we want those four to read as section *headings* (like the
# baselibs / lifecycle home pages) rather than plain links, while still keeping
# the auto-generated nested tree beneath them. pydata renders every toctree
# entry as a link, so we restyle just the first-level entries of the home
# page's toctree to look like headings. The rule is scoped to the home page
# (``#score-rules-for-bazel``) so section pages are unaffected.
_HOME_TOC_CSS = """\
/* Homepage: each top-level group is a real H2 section that references its
   landing page via a toctree. The landing page's own self-link duplicates the
   section heading, so hide it and surface its children directly under the
   heading. */
#score-rules-for-bazel .toctree-wrapper > ul > li.toctree-l1 > a {
  display: none;
}
#score-rules-for-bazel .toctree-wrapper > ul {
  list-style: none;
  padding-left: 0;
  margin: 0;
}
#score-rules-for-bazel .toctree-wrapper > ul > li.toctree-l1 > ul {
  padding-left: 2.5rem;
  margin: 0;
}
/* Second-level entries get a solid (filled) bullet, third-level entries get a
   hollow circle. */
#score-rules-for-bazel .toctree-wrapper > ul > li.toctree-l1 > ul > li,
#score-rules-for-bazel section > ul.simple > li {
  list-style-type: disc;
}
#score-rules-for-bazel .toctree-wrapper li.toctree-l2 ul li,
#score-rules-for-bazel section > ul.simple > li ul li {
  list-style-type: circle;
}
/* The hidden landing self-link's list item must not show a stray marker. */
#score-rules-for-bazel .toctree-wrapper > ul > li.toctree-l1 {
  list-style: none;
}
/* Interior content pages (User Guide index, section landing pages, etc.): the
   body toctree lists the child page at the top level and its sections nested
   beneath. Give the top page entry a solid bullet and every deeper entry a
   hollow circle. Homepage rules above use higher-specificity #id selectors and
   are unaffected. */
article .toctree-wrapper > ul {
  padding-left: 1.5rem;
}
article .toctree-wrapper li.toctree-l1 {
  list-style-type: disc;
}
article .toctree-wrapper li.toctree-l1 li {
  list-style-type: circle;
}
/* Requirement / needs objects: the score_metamodel domain renders each item as
   a definition list whose signature (<dt class="sig ... requirement">) carries
   the anchor "#". By default the pydata theme leaves it unboxed. Wrap each such
   signature in a sky-blue box (matching the RTD original) that stays legible in
   both light and dark mode. */
dl.requirement > dt.sig,
dl.need > dt.sig,
dl.definition > dt.sig.sig-object {
  background-color: var(--score-req-box-bg, #e7f2fa);
  border: 1px solid var(--score-req-box-border, #6ab0de);
  border-radius: 4px;
  padding: 0.4rem 0.6rem;
  margin-bottom: 0.5rem;
}
html[data-theme="dark"] dl.requirement > dt.sig,
html[data-theme="dark"] dl.need > dt.sig,
html[data-theme="dark"] dl.definition > dt.sig.sig-object {
  --score-req-box-bg: rgba(56, 139, 253, 0.15);
  --score-req-box-border: #388bfd;
}
/* LOBSTER traceability report cards. The pydata theme mutes sphinx-design's
   semantic colors, so the status headers ([MISSING]=danger, [OK]=success,
   [PARTIAL]=warning) render as washed-out pink / green / yellow and the
   per-item "Traces to" issue card picks up a dark surface colour that is
   unreadable in light mode. Restore solid, legible status headers and a
   neutral, theme-adaptive issue card that reads well in both light and dark
   mode. */
details.sd-card > summary.sd-bg-danger,
.sd-summary-title.sd-bg-danger {
  background-color: #dc3545 !important;
  color: #fff !important;
}
details.sd-card > summary.sd-bg-success,
.sd-summary-title.sd-bg-success {
  background-color: #2e7d32 !important;
  color: #fff !important;
}
details.sd-card > summary.sd-bg-warning,
.sd-summary-title.sd-bg-warning {
  background-color: #ffc107 !important;
  color: #212529 !important;
}
details.sd-card > summary.sd-bg-danger .sd-summary-text,
details.sd-card > summary.sd-bg-success .sd-summary-text {
  color: #fff !important;
}
details.sd-card > summary.sd-bg-warning .sd-summary-text {
  color: #212529 !important;
}
.lobster-issue-card,
.lobster-issue-card > .sd-card-body {
  background-color: transparent !important;
  border-color: var(--pst-color-border, #ced4da) !important;
}
.lobster-issue-card .sd-card-text,
.lobster-issue-card p {
  color: var(--pst-color-text-base) !important;
}
"""


def setup(app):
    """Register the home-page section styling.

    The stylesheet is written into the build's ``_static`` directory at
    ``build-finished`` (it is not part of a source ``html_static_path``), and
    referenced from every page via ``add_css_file``. This keeps the styling
    self-contained in the conf template with no extra Bazel-staged asset.
    """
    import os

    css_name = "tooling_home.css"
    app.add_css_file(css_name)

    def _emit_css(inner_app, _exception):
        static_dir = os.path.join(inner_app.outdir, "_static")
        os.makedirs(static_dir, exist_ok=True)
        with open(os.path.join(static_dir, css_name), "w", encoding="utf-8") as handle:
            handle.write(_HOME_TOC_CSS)

    app.connect("build-finished", _emit_css)

    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
