"""
Test suite for safety_element_out_of_context macro.

Tests the SEooC (Safety Element out of Context) functionality including:
- Index generation with artifact references
- Integration with score_module
- Sphinx-needs cross-referencing
- HTML output generation
"""

load("@bazel_skylib//lib:unittest.bzl", "analysistest", "asserts")
load("//bazel/rules/score_module/private:score_module.bzl", "ScoreModuleInfo", "ScoreNeedsInfo")

def _seooc_index_generation_test_impl(ctx):
    """Test that SEooC generates proper index.rst file."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Get the generated index file
    files = target_under_test[DefaultInfo].files.to_list()

    # Find index.rst in the output files
    index_file = None
    for f in files:
        if f.basename == "index.rst":
            index_file = f
            break

    # Assert index file exists
    asserts.true(
        env,
        index_file != None,
        "Expected index.rst to be generated by _generate_seooc_index rule",
    )

    return analysistest.end(env)

seooc_index_generation_test = analysistest.make(
    impl = _seooc_index_generation_test_impl,
)

def _seooc_artifacts_copied_test_impl(ctx):
    """Test that all SEooC artifacts are copied to output directory."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    files = target_under_test[DefaultInfo].files.to_list()

    # Expected artifact basenames
    expected_artifacts = [
        "assumptions_of_use.rst",
        "component_requirements.rst",
        "architectural_design.rst",
        "safety_analysis.rst",
    ]

    # Check each artifact exists
    actual_basenames = [f.basename for f in files]
    for artifact in expected_artifacts:
        asserts.true(
            env,
            artifact in actual_basenames,
            "Expected artifact '{}' to be in output files".format(artifact),
        )

    return analysistest.end(env)

seooc_artifacts_copied_test = analysistest.make(
    impl = _seooc_artifacts_copied_test_impl,
)

def _seooc_score_module_generated_test_impl(ctx):
    """Test that SEooC generates score_module with HTML output."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Check that ScoreModuleInfo provider exists
    asserts.true(
        env,
        ScoreModuleInfo in target_under_test,
        "Expected SEooC to provide ScoreModuleInfo from score_module",
    )

    return analysistest.end(env)

seooc_score_module_generated_test = analysistest.make(
    impl = _seooc_score_module_generated_test_impl,
)

def _seooc_needs_provider_test_impl(ctx):
    """Test that SEooC generates needs provider for cross-referencing."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Check that ScoreNeedsInfo provider exists
    asserts.true(
        env,
        ScoreNeedsInfo in target_under_test,
        "Expected SEooC_needs to provide ScoreNeedsInfo",
    )

    return analysistest.end(env)

seooc_needs_provider_test = analysistest.make(
    impl = _seooc_needs_provider_test_impl,
)

def _seooc_description_test_impl(ctx):
    """Test that SEooC includes description in generated index.rst."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Get the generated index file
    files = target_under_test[DefaultInfo].files.to_list()

    # Find index.rst
    index_file = None
    for f in files:
        if f.basename == "index.rst":
            index_file = f
            break

    # Note: We can't easily read file contents in analysis test,
    # but we can verify the file exists. The description content
    # would be validated through integration tests or manual inspection.
    asserts.true(
        env,
        index_file != None,
        "Expected index.rst to exist for description validation",
    )

    return analysistest.end(env)

seooc_description_test = analysistest.make(
    impl = _seooc_description_test_impl,
)
