# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""
Test suite for dependable_element macro.

Tests the SEooC (Safety Element out of Context) functionality including:
- Index generation with artifact references
- Integration with sphinx_module
- Sphinx-needs cross-referencing
- HTML output generation
"""

load("@bazel_skylib//lib:unittest.bzl", "analysistest", "asserts")
load("@score_tooling//bazel/rules/rules_score:providers.bzl", "FeatureRequirementsInfo", "SphinxIndexFileInfo", "SphinxModuleInfo", "SphinxNeedsInfo")

def _seooc_index_generation_test_impl(ctx):
    """Test that dependable_element generates proper index.rst file."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Get the generated index file
    files = target_under_test[DefaultInfo].files.to_list()

    # Find index.rst in the output files
    index_file = None
    for f in files:
        if f.basename == "index.rst":
            index_file = f
            break

    # Assert index file exists
    asserts.true(
        env,
        index_file != None,
        "Expected index.rst to be generated by dependable_element_index rule",
    )

    return analysistest.end(env)

seooc_index_generation_test = analysistest.make(
    impl = _seooc_index_generation_test_impl,
)

def _seooc_artifacts_copied_test_impl(ctx):
    """Test that all dependable element artifacts are copied to output directory."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    files = target_under_test[DefaultInfo].files.to_list()

    # Expected artifact basenames - these come from the SphinxSourcesInfo providers
    # and are filtered to only include .rst/.md files for the index
    expected_artifacts = [
        "feat_req.rst",  # from feature requirements (rendered TRLC → RST)
        "dfa.rst",  # from :dependability_analysis_target
    ]

    # Check each artifact exists
    actual_basenames = [f.basename for f in files]
    for artifact in expected_artifacts:
        asserts.true(
            env,
            artifact in actual_basenames,
            "Expected artifact '{}' to be in output files".format(artifact),
        )

    return analysistest.end(env)

seooc_artifacts_copied_test = analysistest.make(
    impl = _seooc_artifacts_copied_test_impl,
)

def _seooc_sphinx_module_generated_test_impl(ctx):
    """Test that dependable_element generates sphinx_module with HTML output."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Check that SphinxModuleInfo provider exists
    asserts.true(
        env,
        SphinxModuleInfo in target_under_test,
        "Expected dependable_element to provide SphinxModuleInfo from sphinx_module",
    )

    return analysistest.end(env)

seooc_sphinx_module_generated_test = analysistest.make(
    impl = _seooc_sphinx_module_generated_test_impl,
)

def _seooc_needs_provider_test_impl(ctx):
    """Test that dependable_element generates needs provider for cross-referencing."""
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Check that SphinxNeedsInfo provider exists
    asserts.true(
        env,
        SphinxNeedsInfo in target_under_test,
        "Expected dependable_element_needs to provide SphinxNeedsInfo",
    )

    return analysistest.end(env)

seooc_needs_provider_test = analysistest.make(
    impl = _seooc_needs_provider_test_impl,
)

# ============================================================================
# Regression tests: correct index.rst resolution (multi-index scenario)
#
# These tests guard against a bug where the wrong index.rst was picked as the
# Sphinx entry point when multiple index.rst files are present in the output
# tree (e.g. unit/index.rst, component/index.rst alongside the root index.rst).
# The fix is to carry the correct File explicitly via SphinxIndexFileInfo rather
# than scanning all output files for any path ending with "/index.rst".
# ============================================================================

def _seooc_multi_index_files_exist_test_impl(ctx):
    """
    Given a dependable_element with at least one component (which generates
          multiple .rst files in subdirectories alongside the root index.rst),
    When the _index rule finishes,
    Then SphinxIndexFileInfo must be provided and its index_file must be the
         root index.rst (not inside any subdirectory), confirming the correct
         entry point is propagated explicitly rather than discovered by scanning.
    """
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # Then: SphinxIndexFileInfo provider must be present
    asserts.true(
        env,
        SphinxIndexFileInfo in target_under_test,
        "Expected SphinxIndexFileInfo provider to be present on the index target",
    )

    index_file = target_under_test[SphinxIndexFileInfo].index_file

    # Then: the index file must be named index.rst
    asserts.true(
        env,
        index_file.basename == "index.rst",
        "SphinxIndexFileInfo.index_file must be named index.rst, got: " + index_file.basename,
    )

    # Then: the index file must be at the root of the output tree (no subdirectory in dirname)
    # e.g. .../test_dependable_element_index/index.rst — the last path component of dirname
    # must equal the target name, not a sub-page like "components" or "units".
    parent = index_file.dirname.split("/")[-1]
    asserts.true(
        env,
        parent == ctx.attr.target_under_test.label.name,
        "SphinxIndexFileInfo.index_file must sit directly under the target output dir, " +
        "not in a subdirectory. dirname ends in '" + parent + "', expected '" +
        ctx.attr.target_under_test.label.name + "'",
    )

    return analysistest.end(env)

seooc_multi_index_files_exist_test = analysistest.make(
    impl = _seooc_multi_index_files_exist_test_impl,
)

def _seooc_sphinx_entry_point_is_root_index_test_impl(ctx):
    """
    Given a dependable_element whose source tree contains both a root index.rst
          and a components/index.rst,
    When the Sphinx HTML build action is constructed,
    Then the --index_file argument passed to Sphinx must point to the root
         index.rst and must NOT point to the components/index.rst sub-page.
    """
    env = analysistest.begin(ctx)

    # When: inspect all actions produced for this target
    actions = analysistest.target_actions(env)

    # Find the Sphinx HTML action: it is a run() action whose outputs contain
    # the "_html" directory (declared as <name>/_html).
    sphinx_html_action = None
    for action in actions:
        for output in action.outputs.to_list():
            if output.basename == "_html":
                sphinx_html_action = action
                break
        if sphinx_html_action:
            break

    asserts.true(
        env,
        sphinx_html_action != None,
        "Expected to find the Sphinx HTML build action (output ending in '_html')",
    )

    # Then: extract the value that follows --index_file in the argument list
    argv = sphinx_html_action.argv
    index_path = None
    for i, arg in enumerate(argv):
        if arg == "--index_file" and i + 1 < len(argv):
            index_path = argv[i + 1]
            break

    asserts.true(
        env,
        index_path != None,
        "Sphinx HTML action must contain a --index_file argument",
    )

    asserts.true(
        env,
        index_path.endswith("index.rst"),
        "The --index_file value must end with index.rst; got: " + str(index_path),
    )

    asserts.false(
        env,
        "components/" in index_path,
        "The --index_file value must NOT point to components/index.rst; got: " + str(index_path),
    )

    return analysistest.end(env)

seooc_sphinx_entry_point_is_root_index_test = analysistest.make(
    impl = _seooc_sphinx_entry_point_is_root_index_test_impl,
)

def _seooc_all_sources_relocated_test_impl(ctx):
    """
    Given a dependable_element that provides source files via SphinxSourcesInfo,
    When the Sphinx HTML build action is constructed,
    Then all source files must appear as inputs to the action, confirming that
         every file is relocated (symlinked) and none are silently dropped.
    """
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    # When: find the Sphinx HTML action (same selection as the entry-point test)
    actions = analysistest.target_actions(env)
    sphinx_html_action = None
    for action in actions:
        for output in action.outputs.to_list():
            if output.basename == "_html":
                sphinx_html_action = action
                break
        if sphinx_html_action:
            break

    asserts.true(
        env,
        sphinx_html_action != None,
        "Expected to find the Sphinx HTML build action (output ending in '_html')",
    )

    # Then: every .rst / .md / .puml / .json source from the index target's
    # output file set must appear as an input to the HTML action.
    index_files = target_under_test[DefaultInfo].files.to_list()
    source_exts = ("rst", "md", "puml", "plantuml", "json")
    expected_sources = [
        f
        for f in index_files
        if f.extension in source_exts
    ]

    action_input_paths = {f.path: True for f in sphinx_html_action.inputs.to_list()}

    for src in expected_sources:
        asserts.true(
            env,
            src.path in action_input_paths,
            "Source file '{}' was not passed as input to the Sphinx HTML action".format(src.path),
        )

    return analysistest.end(env)

seooc_all_sources_relocated_test = analysistest.make(
    impl = _seooc_all_sources_relocated_test_impl,
)

def _seooc_index_file_provider_test_impl(ctx):
    """
    Given a _dependable_element_index target,
    When its providers are inspected,
    Then SphinxIndexFileInfo must be present and its index_file must be the
         root index.rst (not a components/index.rst sub-page).
    """
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    asserts.true(
        env,
        SphinxIndexFileInfo in target_under_test,
        "_dependable_element_index must provide SphinxIndexFileInfo",
    )

    index_file = target_under_test[SphinxIndexFileInfo].index_file

    asserts.true(
        env,
        index_file.basename == "index.rst",
        "SphinxIndexFileInfo.index_file must be named index.rst; got: " + index_file.basename,
    )

    asserts.false(
        env,
        "components/" in index_file.path,
        "SphinxIndexFileInfo.index_file must NOT point to components/index.rst; got: " + index_file.path,
    )

    return analysistest.end(env)

seooc_index_file_provider_test = analysistest.make(
    impl = _seooc_index_file_provider_test_impl,
)

def _feat_req_system_req_srcs_populated_test_impl(ctx):
    """
    Given a feature_requirements target whose deps include an assumed_system_requirements target,
    When FeatureRequirementsInfo is inspected,
    Then system_req_srcs must be non-empty and contain a .lobster file.
    """
    env = analysistest.begin(ctx)
    target_under_test = analysistest.target_under_test(env)

    asserts.true(
        env,
        FeatureRequirementsInfo in target_under_test,
        "Expected FeatureRequirementsInfo to be provided by feature_requirements target",
    )

    info = target_under_test[FeatureRequirementsInfo]
    system_req_files = info.system_req_srcs.to_list()

    asserts.true(
        env,
        len(system_req_files) > 0,
        "Expected system_req_srcs to be non-empty when feature_requirements has assumed_system_requirements deps",
    )

    lobster_files = [f for f in system_req_files if f.extension == "lobster"]
    asserts.true(
        env,
        len(lobster_files) > 0,
        "Expected system_req_srcs to contain at least one .lobster file; got: " + str([f.basename for f in system_req_files]),
    )

    return analysistest.end(env)

feat_req_system_req_srcs_populated_test = analysistest.make(
    impl = _feat_req_system_req_srcs_populated_test_impl,
)

def _de_lobster_config_includes_system_req_srcs_test_impl(ctx):
    """
    Given a dependable_element whose feature_requirements deps include assumed_system_requirements,
    When the lobster report action is inspected,
    Then the system requirement lobster file must appear as an input to that action.
    """
    env = analysistest.begin(ctx)

    actions = analysistest.target_actions(env)

    # Find the lobster report action: it takes de_traceability_config plus all
    # lobster source files as inputs, and produces the lobster JSON report.
    # Identify it by the presence of de_traceability_config in its inputs.
    lobster_report_action = None
    for action in actions:
        input_basenames = [f.basename for f in action.inputs.to_list()]
        if "de_traceability_config" in input_basenames:
            lobster_report_action = action
            break

    asserts.true(
        env,
        lobster_report_action != None,
        "Expected to find the lobster report action (one whose inputs include de_traceability_config)",
    )

    input_basenames = [f.basename for f in lobster_report_action.inputs.to_list()]
    lobster_inputs = [n for n in input_basenames if n.endswith(".lobster")]

    # The system requirement lobster file (from the asr_trlc fixture target) must be present
    asserts.true(
        env,
        "asr_trlc.lobster" in lobster_inputs,
        "Expected 'asr_trlc.lobster' in lobster report action inputs; got: " + str(lobster_inputs),
    )

    return analysistest.end(env)

de_lobster_config_includes_system_req_srcs_test = analysistest.make(
    impl = _de_lobster_config_includes_system_req_srcs_test_impl,
)
