# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
load("@bazel_skylib//rules:common_settings.bzl", "BuildSettingInfo")
load("@rules_cc//cc:find_cc_toolchain.bzl", "find_cc_toolchain", "use_cc_toolchain")
load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load("@rules_cc//cc/common:cc_info.bzl", "CcInfo")
load(":libclang_toolchain.bzl", "LIBCLANG_TOOLCHAIN_TYPE")

# Providers and aspects used to adapt C/C++ targets for the parser action.

def _extract_files_from_attr(attr, attr_name):
    files = []
    for src in getattr(attr, attr_name, []):
        if hasattr(src, "files"):
            files.extend(src.files.to_list())
    return files

SourceFilesInfo = provider(
    doc = "Source files and transitive inputs collected for parser actions.",
    fields = {
        "files": "depset of source files to parse for this target.",
        "inputs": "depset of source and header inputs needed by the parser action.",
    },
)

def _cc_sources_aspect_impl(target, ctx):
    direct_srcs = _extract_files_from_attr(ctx.rule.attr, "srcs")
    direct_hdrs = _extract_files_from_attr(ctx.rule.attr, "hdrs")
    direct_textual_hdrs = _extract_files_from_attr(ctx.rule.attr, "textual_hdrs")

    transitive_inputs = []
    for dep in getattr(ctx.rule.attr, "deps", []):
        if SourceFilesInfo in dep:
            transitive_inputs.append(dep[SourceFilesInfo].inputs)

    if direct_srcs:
        files = direct_srcs
    else:
        files = []
        files.extend(direct_hdrs)
        files.extend(direct_textual_hdrs)

    direct_inputs = []
    direct_inputs.extend(direct_srcs)
    direct_inputs.extend(direct_hdrs)
    direct_inputs.extend(direct_textual_hdrs)

    return [
        SourceFilesInfo(
            files = depset(files),
            inputs = depset(direct_inputs, transitive = transitive_inputs),
        ),
    ]

cc_sources_aspect = aspect(
    implementation = _cc_sources_aspect_impl,
    attr_aspects = ["deps"],
)

CompilationFlagsInfo = provider(
    doc = "Collected compilation flags for a target and its transitive deps",
    fields = {
        "flags": "depset of compilation flags",
    },
)

CppParserInfo = provider(
    doc = "Outputs generated by the C/C++ parser.",
    fields = {
        "class_fbs": "Class diagram FlatBuffer output file.",
        "debug_json": "Debug JSON sidecar output file. (Optional)",
    },
)

def _collect_from_cc_info(target, ctx):
    flags = []

    if CcInfo in target:
        cc_info = target[CcInfo]

        if hasattr(cc_info, "compilation_context"):
            cc_ctx = cc_info.compilation_context

            flags.extend(["-D%s" % d for d in cc_ctx.defines.to_list()])
            flags.extend(["-D%s" % d for d in cc_ctx.local_defines.to_list()])
            flags.extend(["-I%s" % p for p in cc_ctx.includes.to_list()])
            flags.extend(["-iquote%s" % p for p in cc_ctx.quote_includes.to_list()])
            flags.extend(["-isystem%s" % p for p in cc_ctx.system_includes.to_list()])
            flags.extend(["-isystem%s" % p for p in cc_ctx.external_includes.to_list()])
            flags.extend(["-F%s" % p for p in cc_ctx.framework_includes.to_list()])

    return flags

def _compilation_flags_aspect_impl(target, ctx):
    transitive = []

    for dep in getattr(ctx.rule.attr, "deps", []):
        if CompilationFlagsInfo in dep:
            transitive.append(dep[CompilationFlagsInfo].flags)

    direct_flags = _collect_from_cc_info(target, ctx)

    return [
        CompilationFlagsInfo(
            flags = depset(direct_flags, transitive = transitive),
        ),
    ]

compilation_flags_aspect = aspect(
    implementation = _compilation_flags_aspect_impl,
    attr_aspects = ["deps"],
)

# Public integration helpers for rules that want to reuse the parser action.

def cpp_parser_target_aspects():
    """Return aspects required on attrs whose targets will be parsed."""

    return [cc_sources_aspect, compilation_flags_aspect]

def has_cpp_parser_inputs(target):
    """Check whether a target has the providers needed by run_cpp_parser_action."""

    return (CcInfo in target and
            SourceFilesInfo in target and
            CompilationFlagsInfo in target and
            bool(target[SourceFilesInfo].files.to_list()))

def cpp_parser_action_internal_attrs():
    """Return private attrs required by run_cpp_parser_action callers."""

    return {
        "_tool": attr.label(
            default = Label("//cpp/libclang:clang_rs_parser"),
            executable = True,
            cfg = "exec",
            doc = "Internal libclang-based parser backend.",
        ),
        "_log_level": attr.label(
            default = Label("//cpp/libclang:log_level"),
            doc = "Build setting that controls clang_rs_parser log level.",
        ),
    }

def cpp_parser_action_toolchains():
    """Return toolchain types required by run_cpp_parser_action callers.

    Rules that call run_cpp_parser_action must declare these toolchains so the
    integrating repository's libclang toolchain is resolved for the action.
    """

    return [LIBCLANG_TOOLCHAIN_TYPE]

# Parser action implementation.

def _detect_standard_from_flags(ctx):
    """
    Fall back: compile the action's compile flags and look for -std=.

    This covers toolchains that express the standard via compiler flags
    rather than named features.
    """

    cc_toolchain = find_cc_toolchain(ctx)
    feature_configuration = cc_common.configure_features(
        ctx = ctx,
        cc_toolchain = cc_toolchain,
        # Request every standard feature so configure_features can see them.
        requested_features = ctx.features,
        unsupported_features = ctx.disabled_features,
    )
    compile_variables = cc_common.create_compile_variables(
        feature_configuration = feature_configuration,
        cc_toolchain = cc_toolchain,
        # We only care about the flag shape, not a real file.
        source_file = "/dev/null",
        output_file = "/dev/null",
    )
    flags = cc_common.get_memory_inefficient_command_line(
        feature_configuration = feature_configuration,
        action_name = "c++-compile",
        variables = compile_variables,
    )

    modern_default = "-std=c++11"

    for flag in reversed(flags):
        if flag.startswith("-std="):
            return flag
    return modern_default

def _collect_required_llvm_include_args(cxx_builtin_include_files, extra_config_site_files):
    """
    Build required libc++/clang builtin include flags from LLVM toolchain attributes.

    Derives all paths dynamically from the cxx_builtin_include and extra_config_site
    filegroups exposed by the LLVM toolchain

    Args:
        cxx_builtin_include_files: Files from @llvm_toolchain_llvm//:cxx_builtin_include,
            containing the libc++ headers directory (include/c++) and the clang resource
            include directory (lib/clang/<version>/include).
        extra_config_site_files: Files from @llvm_toolchain_llvm//:extra_config_site,
            containing the arch-specific __config_site file(s) used to locate the ABI
            include directory (include/<triple>/c++/v1).
    """
    libcxx_include = None
    resource_include = None

    for f in cxx_builtin_include_files:
        if "/lib/clang/" in f.path:
            resource_include = f.path
        elif f.path.endswith("/include/c++"):
            libcxx_include = f.path + "/v1"

    if not libcxx_include or not resource_include:
        fail("Could not derive LLVM include paths from cxx_builtin_include filegroup. " +
             "Got files: %s" % [f.path for f in cxx_builtin_include_files])

    resource_dir = resource_include.rpartition("/include")[0]

    result = [
        "-isystem",
        libcxx_include,
    ]

    if len(extra_config_site_files) > 1:
        fail("Expected at most one arch-specific __config_site file, got: %s" %
             [f.path for f in extra_config_site_files])

    for f in extra_config_site_files:
        result += ["-isystem", f.dirname]

    result += [
        "-resource-dir",
        resource_dir,
        "-isystem",
        resource_include,
    ]

    return result

def run_cpp_parser_action(
        ctx,
        *,
        target,
        output_prefix,
        tool,
        log_level,
        extra_args = [],
        emit_debug_json = False):
    """Register the libclang parser action and return its declared outputs.

    The target must be analyzed with cpp_parser_target_aspects() before this
    helper is called. Use has_cpp_parser_inputs() when the caller accepts mixed
    implementation target types. The calling rule must declare the toolchains
    returned by cpp_parser_action_toolchains().
    """

    libclang_info = ctx.toolchains[LIBCLANG_TOOLCHAIN_TYPE].libclang_info
    libclang = libclang_info.libclang

    class_fbs_output = ctx.actions.declare_file(
        "{}_{}".format(output_prefix, "class_diagram.fbs.bin"),
    )

    debug_json_output = None
    if emit_debug_json:
        debug_json_output = ctx.actions.declare_file(
            "{}_{}".format(output_prefix, "debug.json"),
        )

    tool_files_to_run = tool[DefaultInfo].files_to_run

    args = []
    args += [
        "--class-fbs-output",
        class_fbs_output.path,
    ]

    if debug_json_output:
        args += [
            "--debug-json-output",
            debug_json_output.path,
        ]

    target_compilation_flags_list = target[CompilationFlagsInfo].flags.to_list()

    cxx_builtin_include_files = libclang_info.cxx_builtin_include.to_list()
    extra_config_site_files = libclang_info.extra_config_site.to_list()
    llvm_include_args = _collect_required_llvm_include_args(cxx_builtin_include_files, extra_config_site_files)

    parser_extra_args = [
        _detect_standard_from_flags(ctx),
        "-nostdinc++",
    ]
    parser_extra_args += llvm_include_args
    parser_extra_args += target_compilation_flags_list + extra_args
    for ea in parser_extra_args:
        args += ["--extra-arg", ea]

    target_source_files_info = target[SourceFilesInfo]
    target_source_files_list = target_source_files_info.files.to_list()
    target_source_inputs_list = target_source_files_info.inputs.to_list()

    args += ["--input"] + [file.path for file in target_source_files_list]

    inputs = [
        libclang,
    ] + target_source_inputs_list + cxx_builtin_include_files + extra_config_site_files

    outputs = [class_fbs_output]
    if debug_json_output:
        outputs.append(debug_json_output)

    ctx.actions.run(
        inputs = inputs,
        outputs = outputs,
        executable = tool_files_to_run.executable,
        tools = [tool_files_to_run],
        arguments = args,
        env = {
            "LIBCLANG_PATH": libclang.dirname,
            "LIBCLANG_LOG": log_level,
        },
        mnemonic = "CppAnalyze",
        # this is required to parse some system headers
        execution_requirements = {
            "no-sandbox": "1",
        },
        progress_message = "Running C++ AST analysis: %s" % ctx.label,
    )

    return struct(
        class_fbs = class_fbs_output,
        debug_json = debug_json_output,
    )

# cpp_parser rule

def _cpp_parser_impl(ctx):
    if not has_cpp_parser_inputs(ctx.attr.target):
        fail("cpp_parser requires a C/C++ target with non-empty parse inputs: %s" % ctx.attr.target)

    outputs = run_cpp_parser_action(
        ctx,
        target = ctx.attr.target,
        output_prefix = ctx.label.name,
        tool = ctx.attr._tool,
        log_level = ctx.attr._log_level[BuildSettingInfo].value,
        extra_args = ctx.attr.extra_args,
        emit_debug_json = ctx.attr.emit_debug_json,
    )

    runfiles_files = [outputs.class_fbs]
    if outputs.debug_json:
        runfiles_files.append(outputs.debug_json)

    return [
        DefaultInfo(
            files = depset([outputs.class_fbs]),
            runfiles = ctx.runfiles(files = runfiles_files),
        ),
        CppParserInfo(
            class_fbs = outputs.class_fbs,
            debug_json = outputs.debug_json,
        ),
    ]

_cpp_parser_attrs = {
    "target": attr.label(
        aspects = cpp_parser_target_aspects(),
        mandatory = True,
    ),
    "extra_args": attr.string_list(
        default = [],
    ),
    "emit_debug_json": attr.bool(
        default = False,
        doc = "Emit debug.json alongside the FlatBuffer output. Intended for tests/debugging.",
    ),
}

_cpp_parser_attrs.update(cpp_parser_action_internal_attrs())

# BUILD-facing parser rule: wraps run_cpp_parser_action and exposes CppParserInfo.
cpp_parser = rule(
    implementation = _cpp_parser_impl,
    attrs = _cpp_parser_attrs,
    toolchains = cpp_parser_action_toolchains() + use_cc_toolchain(),
    fragments = ["cpp"],
)
