# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
load("@bazel_skylib//rules:common_settings.bzl", "BuildSettingInfo")
load("@rules_cc//cc:action_names.bzl", "ACTION_NAMES")
load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load("@rules_cc//cc/common:cc_info.bzl", "CcInfo")
load(":libclang_toolchain.bzl", "LIBCLANG_TOOLCHAIN_TYPE")

# Providers and aspects used to adapt C/C++ targets for the parser action.

def _extract_files_from_attr(attr, attr_name):
    files = []
    for src in getattr(attr, attr_name, []):
        if hasattr(src, "files"):
            files.extend(src.files.to_list())
    return files

SourceFilesInfo = provider(
    doc = "Source files and transitive inputs collected for parser actions.",
    fields = {
        "files": "depset of source files to parse for this target.",
        "inputs": "depset of source and header inputs needed by the parser action.",
    },
)

def _cc_sources_aspect_impl(target, ctx):
    direct_srcs = _extract_files_from_attr(ctx.rule.attr, "srcs")
    direct_hdrs = _extract_files_from_attr(ctx.rule.attr, "hdrs")
    direct_textual_hdrs = _extract_files_from_attr(ctx.rule.attr, "textual_hdrs")

    transitive_inputs = []
    for dep in getattr(ctx.rule.attr, "deps", []):
        if SourceFilesInfo in dep:
            transitive_inputs.append(dep[SourceFilesInfo].inputs)

    # Also pull in every header CcInfo's compilation_context reports as
    # needed (this is Bazel's own authoritative transitive header set, e.g.
    # including third-party deps' generated "_virtual_includes" symlink
    # trees), not just what the aspect can walk via srcs/hdrs/deps attrs.
    # This matters now that the parser action runs fully sandboxed (no more
    # execution_requirements = {"no-sandbox": "1"} escape hatch): any header
    # transitively required but not declared as an input is invisible.
    if CcInfo in target:
        transitive_inputs.append(target[CcInfo].compilation_context.headers)

    if direct_srcs:
        files = direct_srcs
    else:
        files = []
        files.extend(direct_hdrs)
        files.extend(direct_textual_hdrs)

    direct_inputs = []
    direct_inputs.extend(direct_srcs)
    direct_inputs.extend(direct_hdrs)
    direct_inputs.extend(direct_textual_hdrs)

    return [
        SourceFilesInfo(
            files = depset(files),
            inputs = depset(direct_inputs, transitive = transitive_inputs),
        ),
    ]

cc_sources_aspect = aspect(
    implementation = _cc_sources_aspect_impl,
    attr_aspects = ["deps"],
)

CompilationFlagsInfo = provider(
    doc = "Collected compilation flags for a target and its transitive deps",
    fields = {
        "flags": "depset of compilation flags",
    },
)

CppParserInfo = provider(
    doc = "Outputs generated by the C/C++ parser.",
    fields = {
        "class_fbs": "Class diagram FlatBuffer output file.",
        "debug_json": "Debug JSON sidecar output file. (Optional)",
    },
)

def _collect_from_cc_info(target, ctx):
    flags = []

    if CcInfo in target:
        cc_info = target[CcInfo]

        if hasattr(cc_info, "compilation_context"):
            cc_ctx = cc_info.compilation_context

            flags.extend(["-D%s" % d for d in cc_ctx.defines.to_list()])
            flags.extend(["-D%s" % d for d in cc_ctx.local_defines.to_list()])
            flags.extend(["-I%s" % p for p in cc_ctx.includes.to_list()])
            flags.extend(["-iquote%s" % p for p in cc_ctx.quote_includes.to_list()])
            flags.extend(["-isystem%s" % p for p in cc_ctx.system_includes.to_list()])
            flags.extend(["-isystem%s" % p for p in cc_ctx.external_includes.to_list()])
            flags.extend(["-F%s" % p for p in cc_ctx.framework_includes.to_list()])

    return flags

def _compilation_flags_aspect_impl(target, ctx):
    transitive = []

    for dep in getattr(ctx.rule.attr, "deps", []):
        if CompilationFlagsInfo in dep:
            transitive.append(dep[CompilationFlagsInfo].flags)

    direct_flags = _collect_from_cc_info(target, ctx)

    return [
        CompilationFlagsInfo(
            flags = depset(direct_flags, transitive = transitive),
        ),
    ]

compilation_flags_aspect = aspect(
    implementation = _compilation_flags_aspect_impl,
    attr_aspects = ["deps"],
)

# Public integration helpers for rules that want to reuse the parser action.

def cpp_parser_target_aspects():
    """Return aspects required on attrs whose targets will be parsed."""

    return [cc_sources_aspect, compilation_flags_aspect]

def has_cpp_parser_inputs(target):
    """Check whether a target has the providers needed by run_cpp_parser_action."""

    return (CcInfo in target and
            SourceFilesInfo in target and
            CompilationFlagsInfo in target and
            bool(target[SourceFilesInfo].files.to_list()))

def cpp_parser_action_internal_attrs():
    """Return private attrs required by run_cpp_parser_action callers."""

    return {
        "_tool": attr.label(
            default = Label("//cpp/libclang:clang_rs_parser"),
            executable = True,
            cfg = "exec",
            doc = "Internal libclang-based parser backend.",
        ),
        "_log_level": attr.label(
            default = Label("//cpp/libclang:log_level"),
            doc = "Build setting that controls clang_rs_parser log level.",
        ),
    }

def cpp_parser_action_toolchains():
    """Return toolchain types required by run_cpp_parser_action callers.

    Rules that call run_cpp_parser_action must declare these toolchains so the
    integrating repository's libclang toolchain is resolved for the action.
    """

    return [LIBCLANG_TOOLCHAIN_TYPE]

# Parser action implementation.

def _strip_source_file_flag(flags, source_file):
    """Drop the translation-unit's own source file from a derived flag list.

    clang-rs's Index::parser() already supplies the real translation-unit
    filename via the libclang API separately from these --extra-arg flags.
    If the cc_toolchain's cpp_header_parsing action_config also names that
    same file on the command line, libclang ends up seeing the translation
    unit specified both ways, which its parseTranslationUnit machinery cannot
    handle and fails with a CXError_ASTReadError ("AST deserialization
    failed").

    Two forms occur depending on the toolchain:
      * a "-c <source_file>" pair (older toolchains_llvm, e.g. 1.6.0), and
      * a bare positional "<source_file>" argument (toolchains_llvm >= 1.8.0,
        whose c++-header-parsing action embeds the input file directly).
    Both are filtered out here so the flags are safe to reuse regardless of
    which cc_toolchain produced them.
    """
    result = []
    skip_next = False
    for i, flag in enumerate(flags):
        if skip_next:
            skip_next = False
            continue
        if flag == "-c" and i + 1 < len(flags) and flags[i + 1] == source_file:
            skip_next = True
            continue
        if flag == source_file:
            continue
        result.append(flag)
    return result

def _get_hermetic_parser_flags(ctx, cc_toolchain, user_compile_flags, source_file):
    """Derive the clang flags needed to parse a target hermetically.

    Reuses the exact hermetic flags (target triple, resource-dir, sysroot,
    stdlib, -std, ...) that a normal C++ compile with the libclang toolchain's
    registered cc_toolchain would use, instead of hand-parsing LLVM installation
    file layouts. This makes the parser action work with any cc_toolchain
    (LLVM or otherwise) referenced by the libclang_toolchain.

    Uses the toolchain's dedicated "c++-header-parsing" action_config
    (ACTION_NAMES.cpp_header_parsing) rather than "c++-compile". This is the
    same action Bazel's built-in `parse_headers` feature uses to syntax-check
    a header standalone: its flag set is -fsyntax-only-style by construction.
    Some cc_toolchains embed the translation unit's own source file directly
    in this action's flags - either as a "-c <source_file>" pair (e.g.
    toolchains_llvm < 1.8.0) or as a bare positional argument (e.g.
    toolchains_llvm >= 1.8.0). _strip_source_file_flag() removes both forms
    since clang-rs already supplies the real file separately (see below); if
    left in, libclang treats the translation unit as specified twice and
    fails with a CXError_ASTReadError ("AST deserialization failed").

    source_file must be a real source path (not a placeholder like /dev/null)
    and output_file must be left unset: clang-rs's Index::parser() already
    supplies the real translation-unit filename via the libclang API
    separately from these --extra-arg flags, so any -c/-o pair embedded here
    would make clang try to compile a second, conflicting file.

    Also explicitly appends -isystem for each of the cc_toolchain's
    built_in_include_directories (e.g. its bundled libc++ headers,
    resource-dir, and - once cc_toolchain.sysroot is set - the sysroot's own
    include directories). Normally a compiler binary auto-detects these
    relative to its own on-disk location, but here libclang.so is dlopen()'d
    in-process by the clang_rs_parser Rust binary rather than executed as
    `clang`, so that auto-detection resolves relative to the Rust binary's
    path instead and silently fails to find them (e.g. "'vector' file not
    found").
    """
    feature_configuration = cc_common.configure_features(
        ctx = ctx,
        cc_toolchain = cc_toolchain,
        requested_features = ctx.features,
        unsupported_features = ctx.disabled_features,
    )
    compile_variables = cc_common.create_compile_variables(
        feature_configuration = feature_configuration,
        cc_toolchain = cc_toolchain,
        source_file = source_file,
        user_compile_flags = user_compile_flags,
        use_pic = True,
    )
    flags = cc_common.get_memory_inefficient_command_line(
        feature_configuration = feature_configuration,
        action_name = ACTION_NAMES.cpp_header_parsing,
        variables = compile_variables,
    )
    isystem_flags = []
    for include_dir in cc_toolchain.built_in_include_directories:
        isystem_flags.append("-isystem")
        isystem_flags.append(include_dir)
    flags = _strip_source_file_flag(flags, source_file)
    return flags + isystem_flags

def run_cpp_parser_action(
        ctx,
        *,
        target,
        output_prefix,
        tool,
        log_level,
        extra_args = [],
        emit_debug_json = False):
    """Register the libclang parser action and return its declared outputs.

    The target must be analyzed with cpp_parser_target_aspects() before this
    helper is called. Callers MUST check has_cpp_parser_inputs(target) before
    calling this: it derives its hermetic flags from the target's first
    source file, so a target with an empty SourceFilesInfo.files list (e.g. a
    header-only target with no headers reachable from srcs/hdrs/CcInfo) would
    otherwise crash on an out-of-bounds list access. The calling rule must
    declare the toolchains returned by cpp_parser_action_toolchains().
    """

    libclang_info = ctx.toolchains[LIBCLANG_TOOLCHAIN_TYPE].libclang_info
    libclang = libclang_info.libclang
    cc_toolchain = libclang_info.cc_toolchain

    class_fbs_output = ctx.actions.declare_file(
        "{}_{}".format(output_prefix, "class_diagram.fbs.bin"),
    )

    debug_json_output = None
    if emit_debug_json:
        debug_json_output = ctx.actions.declare_file(
            "{}_{}".format(output_prefix, "debug.json"),
        )

    tool_files_to_run = tool[DefaultInfo].files_to_run

    args = []
    args += [
        "--class-fbs-output",
        class_fbs_output.path,
    ]

    if debug_json_output:
        args += [
            "--debug-json-output",
            debug_json_output.path,
        ]

    target_compilation_flags_list = target[CompilationFlagsInfo].flags.to_list()

    target_source_files_info = target[SourceFilesInfo]
    target_source_files_list = target_source_files_info.files.to_list()
    target_source_inputs_list = target_source_files_info.inputs.to_list()

    if not target_source_files_list:
        fail("run_cpp_parser_action requires a target with non-empty parse " +
             "inputs (caller must check has_cpp_parser_inputs() first): %s" % target.label)

    parser_extra_args = _get_hermetic_parser_flags(
        ctx,
        cc_toolchain,
        target_compilation_flags_list + extra_args,
        target_source_files_list[0].path,
    )
    for ea in parser_extra_args:
        args += ["--extra-arg", ea]

    args += ["--input"] + [file.path for file in target_source_files_list]

    inputs = [
        libclang,
    ] + target_source_inputs_list + cc_toolchain.all_files.to_list()

    outputs = [class_fbs_output]
    if debug_json_output:
        outputs.append(debug_json_output)

    ctx.actions.run(
        inputs = inputs,
        outputs = outputs,
        executable = tool_files_to_run.executable,
        tools = [tool_files_to_run],
        arguments = args,
        env = {
            "LIBCLANG_PATH": libclang.dirname,
            "LIBCLANG_LOG": log_level,
        },
        mnemonic = "CppAnalyze",
        progress_message = "Running C++ AST analysis: %s" % ctx.label,
    )

    return struct(
        class_fbs = class_fbs_output,
        debug_json = debug_json_output,
    )

# cpp_parser rule

def _cpp_parser_impl(ctx):
    if not has_cpp_parser_inputs(ctx.attr.target):
        fail("cpp_parser requires a C/C++ target with non-empty parse inputs: %s" % ctx.attr.target)

    outputs = run_cpp_parser_action(
        ctx,
        target = ctx.attr.target,
        output_prefix = ctx.label.name,
        tool = ctx.attr._tool,
        log_level = ctx.attr._log_level[BuildSettingInfo].value,
        extra_args = ctx.attr.extra_args,
        emit_debug_json = ctx.attr.emit_debug_json,
    )

    runfiles_files = [outputs.class_fbs]
    if outputs.debug_json:
        runfiles_files.append(outputs.debug_json)

    return [
        DefaultInfo(
            files = depset([outputs.class_fbs]),
            runfiles = ctx.runfiles(files = runfiles_files),
        ),
        CppParserInfo(
            class_fbs = outputs.class_fbs,
            debug_json = outputs.debug_json,
        ),
    ]

_cpp_parser_attrs = {
    "target": attr.label(
        aspects = cpp_parser_target_aspects(),
        mandatory = True,
    ),
    "extra_args": attr.string_list(
        default = [],
    ),
    "emit_debug_json": attr.bool(
        default = False,
        doc = "Emit debug.json alongside the FlatBuffer output. Intended for tests/debugging.",
    ),
}

_cpp_parser_attrs.update(cpp_parser_action_internal_attrs())

# BUILD-facing parser rule: wraps run_cpp_parser_action and exposes CppParserInfo.
cpp_parser = rule(
    implementation = _cpp_parser_impl,
    attrs = _cpp_parser_attrs,
    toolchains = cpp_parser_action_toolchains(),
    fragments = ["cpp"],
)
