# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""Update runner: refresh coverage.lock.yaml from current gtest.lobster output.

Environment variables
---------------------
REQ_COVERAGE_LOBSTER_MANIFEST
    Path to a newline-delimited file listing lobster-req-trace JSON paths
    (one per line).  Requirement IDs are extracted from these files.
REQ_COVERAGE_GTEST_LOBSTER
    Path to the gtest.lobster file produced by subrule_lobster_gtest.
REQ_COVERAGE_LOCK_FILE
    Workspace-relative path of the committed lock YAML file to overwrite.
REQ_COVERAGE_LABEL
    Bazel label of the req_coverage target (used in log output only).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from req_coverage.compute_lock import compute_lock, serialize
from req_coverage.check_lock import validate_specs
from req_coverage.read_gtest_lobster import (
    read_req_metadata_from_lobster_files,
    resolve_path,
    scan_gtest_lobster,
)


def _require_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        print(f"ERROR: {name} is required", file=sys.stderr)
        sys.exit(1)
    return value


def main() -> None:
    lobster_manifest = resolve_path(_require_env("REQ_COVERAGE_LOBSTER_MANIFEST"))
    gtest_lobster_path = resolve_path(_require_env("REQ_COVERAGE_GTEST_LOBSTER"))
    # The lock file must be resolved to the source tree so that ``bazel run``
    # overwrites the committed file.  ``$BUILD_WORKSPACE_DIRECTORY`` is set
    # by Bazel for all ``bazel run`` invocations; the env var carries the
    # package-relative path (e.g. ``score/message_passing/coverage.lock.yaml``).
    _raw_lock = _require_env("REQ_COVERAGE_LOCK_FILE")
    build_workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if build_workspace:
        lock_file_path = Path(build_workspace) / _raw_lock
    else:
        lock_file_path = resolve_path(_raw_lock)
    label = os.environ.get("REQ_COVERAGE_LABEL", "<unknown>")
    package = os.environ.get("REQ_COVERAGE_PACKAGE", "")

    # Step 1: extract requirement metadata from TRLC lobster output (CompReq only)
    req_metadata = read_req_metadata_from_lobster_files(lobster_manifest)
    if not req_metadata:
        print(
            f"WARNING: [{label}] No CompReq requirement IDs found in lobster manifest.",
            file=sys.stderr,
        )

    req_ids = [m.id for m in req_metadata]

    # Step 2: scan gtest.lobster for test records
    by_req = scan_gtest_lobster(gtest_lobster_path, req_ids, package=package)

    # Warn about requirements with no linked tests (D-7)
    for req_id, records in by_req.items():
        if not records:
            print(
                f"WARNING: [{label}] Requirement {req_id!r} has no linked test cases "
                "in the scanned XML files.",
                file=sys.stderr,
            )

    # Step 3: compute lock
    lock = compute_lock(req_metadata, by_req)

    # Step 3b: warn about missing GWT specs (informational on update)
    spec_ok, spec_issues = validate_specs(lock)
    if not spec_ok:
        print(
            "WARNING: One or more test cases are missing GWT spec annotations:",
            file=sys.stderr,
        )
        for line in spec_issues:
            print(line, file=sys.stderr)

    # Step 4: write lock file
    yaml_content = serialize(lock)
    header = (
        f"# coverage.lock.yaml — auto-generated by req_coverage\n"
        f"# Run `bazel run {label}.update` to refresh.\n"
    )
    lock_file_path.write_text(header + yaml_content, encoding="utf-8")

    print(f"[{label}] Lock file updated: {lock_file_path}")
    for req in lock.requirements:
        print(f"  {req.id}: {len(req.test_cases)} test case(s)")


if __name__ == "__main__":
    main()
