# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
filegroup(
    name = "grammar_files",
    srcs = [
        ":class_grammar",
        ":common_grammar",
        ":component_grammar",
        ":include_grammar",
        ":procedure_grammar",
        ":sequence_grammar",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "include_grammar",
    srcs = [
        "include.pest",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "procedure_grammar",
    srcs = [
        "procedure.pest",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "component_grammar",
    srcs = [
        "component.pest",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sequence_grammar",
    srcs = [
        "sequence.pest",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "class_grammar",
    srcs = [
        "class.pest",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "common_grammar",
    srcs = [
        "common.pest",
    ],
    visibility = ["//visibility:public"],
)
