// *******************************************************************************
// Copyright (c) 2026 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// *******************************************************************************

///////////////////////////////////////////////////////////////
// BASE
///////////////////////////////////////////////////////////////
color      = _{ BASIC_COLOR }

raw_label = @{ (!("\n" | "\r") ~ ANY)+ }
label = { STRING | raw_label }

class_visibility = { "+" | "-" | "#" | "~" }

///////////////////////////////////////////////////////////////
// Name & Alias
///////////////////////////////////////////////////////////////
type_name = { type_expr }

type_expr = { brace_enclosed_type | const_prefix* ~ prefix_array_prefix* ~ qualified_type ~ generic_type_args? ~ function_type_suffix? ~ type_suffix* }

qualified_type = @{ ("::")? ~ identifier ~ (("::" | (!".." ~ ".")) ~ identifier)* }

generic_type_args = { "<" ~ !"<" ~ type_arg ~ ("," ~ type_arg)* ~ ">" }

type_arg = { type_expr | NUMBER }
type_expr_list = { type_expr ~ ("," ~ type_expr)* }

type_suffix = { array_suffix | reference_suffix | pointer_suffix }
brace_enclosed_type = { "{" ~ type_expr ~ "}" }
const_prefix = { "const" }
function_type_suffix = { "(" ~ type_expr_list? ~ ")" }
prefix_array_prefix = { "[" ~ "]" }
array_suffix = { "[" ~ (NUMBER | identifier)? ~ "]" }
reference_suffix = { "&&" | "&" }
pointer_suffix = { "*" }

class_qualified_name = @{ ("::")? ~ identifier ~ ("::" ~ identifier)* }

// reference
name_ref = @{ identifier }

// definition
internal_name = { STRING | generic_decl_name | class_qualified_name }
generic_decl_name = { class_qualified_name ~ type_generic_param_list }

// name_decl = { internal_name ~ ("as" ~ display_name)? }
name_decl = { internal_name ~ alias_clause? }
name_with_color = { name_decl ~ color? }

named = { name_with_color }
link_annotation = { "[[" ~ (!"]]" ~ ANY)+ ~ "]]" }

///////////////////////////////////////////////////////////////
// File-level structure
///////////////////////////////////////////////////////////////
class_start = {
    SOI
    ~ (COMMENT | empty_line)*
    ~ startuml
    ~ EOL*
    ~ (top_level ~ EOL* | ignored_block ~ EOL* | ignored_stmt ~ EOL+ | class_ignored_stmt ~ EOL+)*
    ~ EOL*
    ~ enduml
    ~ EOI
}

class_ignored_stmt = _{
    shared_hide_show_empty_member_core
}

top_level = {
      namespace_def
    | type_def
    | unsupported_object_def
    | enum_def
    | package_def
    | together_def
    | legend_block
    | note_declaration
    | relationship
}

together_def = {
    "together"
    ~ "{"
    ~ EOL*
    ~ (top_level ~ EOL*)*
    ~ EOL*
    ~ "}"
}

///////////////////////////////////////////////////////////////
// namespace / package
///////////////////////////////////////////////////////////////

// namespace_def = { "namespace" ~ named ~ stereotype? ~ "{" ~ EOL* ~ top_level* ~ EOL* ~ "}" }
namespace_def = {
    "namespace"
    ~ named
    ~ stereotype?
    ~ EOL*
    ~ "{"
    ~ EOL*
    ~ (top_level ~ EOL*)*
    ~ EOL*
    ~ "}"
}

package_def = {
    "package"
    ~ named
    ~ stereotype?
    ~ EOL*
    ~ "{"
    ~ EOL*
    ~ (top_level ~ EOL*)*
    ~ EOL*
    ~ "}"
}

///////////////////////////////////////////////////////////////
// type definition
///////////////////////////////////////////////////////////////
type_def = { type_def_with_body | type_def_decl }
unsupported_object_def = { object_def_with_body | object_def_decl }

type_def_decl = { type_kind ~ named ~ type_decl_suffix* }
object_def_decl = { "object" ~ named ~ type_decl_suffix* }
type_decl_suffix = _{ extends_clause | implements_clause | link_annotation | stereotype | color }
template_param = @{ identifier ~ varargs? }
template_param_list = _{ "<" ~ template_param ~ ("," ~ template_param)* ~ ">" }
type_generic_param_list = { template_param_list }

extends_clause = { "extends" ~ extends_target ~ ("," ~ extends_target)* }
extends_target = { class_qualified_name }
implements_clause = { "implements" ~ implements_target ~ ("," ~ implements_target)* }
implements_target = { class_qualified_name }

type_def_with_body = { type_def_decl ~ &(EOL* ~ "{") ~ EOL* ~ class_body ~ ";"? }
object_def_with_body = { object_def_decl ~ &(EOL* ~ "{") ~ EOL* ~ class_body ~ ";"? }
type_kind = {
      "abstract" ~ "class"
    | "class"
    | "struct"
    | "interface"
}

class_body = { "{" ~ EOL* ~ (ignored_mock_method_stmt | class_member | class_body_separator)* ~ EOL* ~ "}" }

class_member = { (method | attribute) ~ EOL+ }
class_body_separator = { "--" ~ EOL+ }

ignored_mock_method_stmt = _{
    method_modifier*
    ~ class_visibility?
    ~ method_modifier*
    ~ mock_method_invocation
    ~ ";"?
    ~ EOL+
}

mock_method_invocation = {
    mock_method_modern_invocation
    | mock_method_legacy_invocation
}

mock_method_modern_invocation = {
    mock_method_modern_macro
    ~ "("
    ~ EOL*
    ~ mock_method_return_type
    ~ EOL*
    ~ ","
    ~ EOL*
    ~ mock_method_name
    ~ EOL*
    ~ ","
    ~ EOL*
    ~ mock_method_param_group
    ~ (EOL* ~ "," ~ EOL* ~ mock_method_modifiers)?
    ~ EOL*
    ~ ")"
}

mock_method_legacy_invocation = {
    mock_method_legacy_with_calltype_invocation
    | mock_method_legacy_without_calltype_invocation
}

mock_method_legacy_with_calltype_invocation = {
    mock_method_legacy_macro_with_calltype
    ~ "("
    ~ EOL*
    ~ mock_method_calltype_value
    ~ EOL*
    ~ ","
    ~ EOL*
    ~ mock_method_name
    ~ EOL*
    ~ ","
    ~ EOL*
    ~ mock_method_legacy_signature
    ~ EOL*
    ~ ")"
}

mock_method_legacy_without_calltype_invocation = {
    mock_method_legacy_macro_without_calltype
    ~ "("
    ~ EOL*
    ~ mock_method_name
    ~ EOL*
    ~ ","
    ~ EOL*
    ~ mock_method_legacy_signature
    ~ EOL*
    ~ ")"
}

mock_method_modern_macro = @{ "MOCK_METHOD" }
mock_method_legacy_macro_with_calltype = @{ ("MOCK_METHOD" | "MOCK_CONST_METHOD") ~ ASCII_DIGIT+ ~ ("_WITH_CALLTYPE" | "_T_WITH_CALLTYPE") }
mock_method_legacy_macro_without_calltype = @{ ("MOCK_METHOD" | "MOCK_CONST_METHOD") ~ ASCII_DIGIT+ ~ "_T"? }

mock_method_calltype_value = @{ (!("," | ")" | EOL) ~ ANY)+ }

mock_method_legacy_signature = {
    mock_method_legacy_return_type
    ~ mock_method_param_group
}

mock_method_legacy_return_type = {
    mock_method_parenthesized_return_type
    | mock_method_legacy_simple_return_type
}

mock_method_legacy_simple_return_type = {
    const_prefix*
    ~ prefix_array_prefix*
    ~ qualified_type
    ~ generic_type_args?
    ~ type_suffix*
}

mock_method_name = { method_name }

mock_method_return_type = {
    mock_method_parenthesized_return_type
    | type_name
}

mock_method_parenthesized_return_type = {
    "("
    ~ EOL*
    ~ type_name
    ~ EOL*
    ~ ")"
}

mock_method_param_group = {
    "("
    ~ EOL*
    ~ param_list?
    ~ EOL*
    ~ ")"
}

mock_method_modifiers = {
    "("
    ~ EOL*
    ~ mock_method_modifier_list?
    ~ EOL*
    ~ ")"
}

mock_method_modifier_list = {
    mock_method_modifier
    ~ (EOL* ~ mock_method_modifier_separator ~ EOL* ~ mock_method_modifier)*
}

mock_method_modifier_separator = _{
    ","
}

mock_method_modifier = {
    method_qualifier
    | mock_method_ref_qualifier
    | mock_method_calltype_qualifier
}

mock_method_ref_qualifier = @{ "ref(" ~ ("&" | "&&") ~ ")" }
mock_method_calltype_qualifier = @{ "Calltype(" ~ class_qualified_name ~ ")" }

method = {
    method_modifier*
    ~ class_visibility?
    ~ friend_specifier?
    ~ method_modifier*
    ~ !mock_method_invocation
    ~ method_name
    ~ generic_param_list?
    ~ "("
    ~ EOL*
    ~ param_list?
    ~ EOL*
    ~ ")"
    ~ generic_param_list?
    ~ method_qualifier*
    ~ return_type?
    ~ method_qualifier*
    ~ pure_virtual_suffix?
    ~ ";"?
}
friend_specifier = { "friend" }
method_modifier = _{ static_modifier | abstract_modifier | virtual_modifier | override_modifier }
static_modifier = { "{" ~ static_keyword ~ "}" | ("<<" ~ static_keyword ~ ">>") | static_keyword }
static_keyword = { "static" }
abstract_modifier = { "{" ~ "abstract" ~ "}" | ("<<" ~ "abstract" ~ ">>") }
virtual_modifier = { "{" ~ "virtual" ~ "}" | ("<<" ~ "virtual" ~ ">>") }
override_modifier = { "{" ~ "override" ~ "}" | ("<<" ~ "override" ~ ">>") }
method_qualifier = _{
    const_method_qualifier
    | noexcept_method_qualifier
    | trailing_override_qualifier
    | final_method_qualifier
}
const_method_qualifier = { ("<<" ~ "const" ~ ">>") | "const" }
noexcept_method_qualifier = { "noexcept" }
trailing_override_qualifier = { "override" }
final_method_qualifier = { ("<<" ~ "final" ~ ">>") | "final" }
pure_virtual_suffix = { "=" ~ "0" }

method_name = {
    operator_overload_name
    | destructor_name
    | class_qualified_name
}
destructor_name = @{ "~" ~ identifier }
operator_overload_name = @{
        "operator"
        ~ (
            "->*"
            | "->"
            | "()"
            | "[]"
            | "<=>"
            | "<<"
            | ">>"
            | "<="
            | ">="
            | "=="
            | "!="
            | "&&"
            | "||"
            | "+="
            | "-="
            | "*="
            | "/="
            | "%="
            | "^="
            | "&="
            | "|="
            | "++"
            | "--"
            | "+"
            | "-"
            | "*"
            | "/"
            | "%"
            | "^"
            | "&"
            | "|"
            | "~"
            | "!"
            | "="
            | "<"
            | ">"
            | ","
        )
}
return_type = { ":" ~ static_modifier* ~ type_name }

attribute = { static_modifier* ~ class_visibility? ~ (using_attribute | named_attribute | unnamed_attribute) }
attribute_end = _{ ";"? ~ &(WHITESPACE* ~ (EOL | "}")) }
using_attribute = { "using" ~ identifier ~ "=" ~ type_name ~ attribute_end }
named_attribute = { identifier ~ (":" ~ attribute_type_specifier* ~ type_name)? ~ attribute_end }
unnamed_attribute = { type_name ~ attribute_end }
attribute_type_specifier = _{ static_modifier | constexpr_modifier }
constexpr_modifier = { "constexpr" }

param = {
    param_named
  | param_cpp_named
  | param_unnamed
}

param_named = {
    identifier
    ~ ":"
    ~ type_name
    ~ param_default_value?
}

param_cpp_named = {
    type_name
    ~ identifier
    ~ param_default_value?
}

param_unnamed = {
    type_name
    ~ param_default_value?
}
typed_param_pack = { param ~ varargs }
c_variadic_param = { varargs }
param_default_value = { "=" ~ (!("," | ")" | EOL) ~ ANY)* }
param_list = {
    (typed_param_pack | c_variadic_param | param)
    ~ (EOL* ~ "," ~ EOL* ~ (typed_param_pack | c_variadic_param | param))*
}

generic_param_list = { template_param_list }
varargs = { "..." }

///////////////////////////////////////////////////////////////
// type definition
///////////////////////////////////////////////////////////////
enum_def = { "enum" ~ named ~ stereotype? ~ enum_body? ~ ";"? }

enum_body = { "{" ~ EOL* ~ enum_item* ~ EOL* ~ "}" }

enum_item = { identifier ~ enum_value? ~ EOL+ }

enum_value = { ( "=" | ":" ) ~ enum_value_literal }

enum_value_literal = @{ (!("\n" | "}") ~ ANY)+ }

///////////////////////////////////////////////////////////////
// Relationship
///////////////////////////////////////////////////////////////

qualified_identifier = @{ name_ref ~ ("." ~ name_ref)+ }
relationship_multiplicity = { STRING }

relationship = {
    (qualified_identifier | name_ref)
    ~ relationship_multiplicity?
    ~ connection_arrow
    ~ relationship_multiplicity?
    ~ (qualified_identifier | name_ref)
    ~ (":" ~ label)?
}
