@startuml

skinparam linetype ortho
skinparam artifact<<document>> {
    BackgroundColor LightGreen
    BorderColor Green
}
skinparam component<<rule>> {
    BackgroundColor LightBlue
    BorderColor Blue
}

component "sphinx_module" as SM <<rule>>

component "bzlmod" as bzlmod <<rule>>
component "score_component" as score_component <<rule>>
component "score_unit" as score_unit <<rule>>

' sphinx_module structure

' module-specific artifacts
artifact "manuals" as score_manual <<document>>
artifact "dependability_management" as dependability_management <<document>>
artifact release_notes <<document>>


' score_component-specific artifacts
artifact "Assumptions of Use" as assumptions_of_use <<document>>
artifact "Component Requirements" as component_requirements <<document>>
artifact "Architecture Design" as architectural_design <<document>>
artifact "Dependability Analysis" as dependability_analysis <<document>>
artifact "Checklists" as checklists <<document>>
artifact "VerificationReport" as verification_report <<document>>

artifact "Detailed Design" as detailed_design <<document>>


' Implementation artifacts
card "Implementation" as Impl <<cc_library>>
card "Test Suite" as Test <<cc_test>>
bzlmod *-- score_component
SM <|-up- score_component

' Relationships for bzlmod
bzlmod *-- score_manual
bzlmod *-- dependability_management
bzlmod *-- release_notes
bzlmod *-- checklists
bzlmod *-- verification_report


' Relationships for score_component
score_component *-- assumptions_of_use
score_component *-- component_requirements
score_component *-- architectural_design
score_component *-- dependability_analysis
score_component *-- Impl
score_component *-- Test
score_component *-- score_unit
score_component *-- checklists
score_component *-- score_component
score_component --> verification_report : creates


score_unit *-- detailed_design



' Cross-module dependencies
SM ..> SM : can depend on

@enduml
