' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

package "Integrator SEooC" as integrator_seooc <<SEooC>> {
    component "IntegratorComponent" as integrator_component <<component>> {
        component "IntegratorUnit" as integrator_unit <<unit>>
    }
}

@enduml
