#!/bin/sh
# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
#
# Runfiles-aware launcher generated by the exec_in_sysroot rule.
#
# It resolves the extracted sysroot TreeArtifact and the shared
# exec_in_sysroot.sh wrapper from its own runfiles (via the $0.runfiles/
# convention, independent of any RUNFILES_DIR the parent process may carry),
# then execs the wrapper with the sysroot-relative binary path.
#
# The following tokens are substituted at analysis time by ctx.actions.expand_template:
#   {{WRAPPER_SHORT_PATH}} - rlocation key of exec_in_sysroot.sh (_fakechroot_wrapper)
#   {{SYSROOT_SHORT_PATH}} - rlocation key of the extracted sysroot TreeArtifact
#   {{SYSROOT_BINARY}}     - sysroot-absolute path of the ELF binary to run
#   {{EXCLUDE_PATHS}}      - colon-separated FAKECHROOT_EXCLUDE_PATH entries (may be empty)
set -eu

# --- begin POSIX sh runfiles init ---
# Prefer $0.runfiles/ (the companion directory Bazel creates for this specific
# binary) over any inherited RUNFILES_DIR from the parent process.  When this
# launcher is invoked as a subprocess from another tool (e.g. Sphinx via
# sphinx.ext.graphviz or PlantUML's -graphvizdot), the parent process carries
# its own RUNFILES_DIR pointing at a different binary's runfiles tree.  The
# standard bootstrap guard (if [ ! -d "${RUNFILES_DIR:-/dev/null}" ]) would
# accept the inherited value and cause rlocation to search the wrong tree,
# failing to find the sysroot.
#
# By probing $0.runfiles/ first we always use this binary's own companion
# runfiles directory when it exists (Bazel creates it whenever this binary is
# used as an action tool or via bazel run).  We fall through to the inherited
# RUNFILES_DIR/RUNFILES_MANIFEST_FILE only when $0.runfiles/ does not exist,
# which happens when this binary is accessed via another target's data dep (e.g.
# the smoke test resolves it via rlocation and the path is inside the test's
# runfiles tree, where no companion .runfiles/ is created).
if [ -d "$0.runfiles" ]; then
  RUNFILES_DIR="$0.runfiles"; export RUNFILES_DIR
  unset RUNFILES_MANIFEST_FILE 2>/dev/null || true
elif [ -f "$0.runfiles_manifest" ]; then
  RUNFILES_MANIFEST_FILE="$0.runfiles_manifest"; export RUNFILES_MANIFEST_FILE
  unset RUNFILES_DIR 2>/dev/null || true
elif [ -f "$0.runfiles/MANIFEST" ]; then
  RUNFILES_MANIFEST_FILE="$0.runfiles/MANIFEST"; export RUNFILES_MANIFEST_FILE
  unset RUNFILES_DIR 2>/dev/null || true
elif [ ! -d "${RUNFILES_DIR:-/dev/null}" ] && [ ! -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]; then
  echo >&2 "ERROR: cannot find runfiles for $0"
  exit 1
fi
rlocation() {
  if [ -n "${RUNFILES_DIR:-}" ] && [ -e "${RUNFILES_DIR}/$1" ]; then
    printf '%s' "${RUNFILES_DIR}/$1"
  elif [ -n "${RUNFILES_MANIFEST_FILE:-}" ]; then
    grep -m1 "^$1 " "${RUNFILES_MANIFEST_FILE}" | cut -d' ' -f2-
  fi
}
# --- end POSIX sh runfiles init ---

FAKECHROOT_WRAPPER="$(rlocation '{{WRAPPER_SHORT_PATH}}')"
SYSROOT_DIR="$(rlocation '{{SYSROOT_SHORT_PATH}}')"

if [ -z "${FAKECHROOT_WRAPPER}" ] || [ ! -x "${FAKECHROOT_WRAPPER}" ]; then
  echo "ERROR: could not resolve fakechroot wrapper: {{WRAPPER_SHORT_PATH}}" >&2
  exit 1
fi

if [ -z "${SYSROOT_DIR}" ] || [ ! -d "${SYSROOT_DIR}" ]; then
  echo "ERROR: could not resolve sysroot directory: {{SYSROOT_SHORT_PATH}}" >&2
  exit 1
fi

export SYSROOT_DIR
if [ -n "{{EXCLUDE_PATHS}}" ]; then
  export FAKECHROOT_EXCLUDE_PATH="{{EXCLUDE_PATHS}}"
fi

exec "${FAKECHROOT_WRAPPER}" "{{SYSROOT_BINARY}}" "$@"
