#!/bin/sh
# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
#
# Runfiles-aware launcher generated by the exec_in_sysroot rule.
#
# It resolves the extracted sysroot TreeArtifact and the shared
# exec_in_sysroot.sh wrapper from its own runfiles (via the $0.runfiles/
# convention, independent of any RUNFILES_DIR the parent process may carry),
# then execs the wrapper with the sysroot-relative binary path.
#
# The following tokens are substituted at analysis time by ctx.actions.expand_template:
#   {{WRAPPER_SHORT_PATH}} - rlocation key of exec_in_sysroot.sh (_fakechroot_wrapper)
#   {{SYSROOT_SHORT_PATH}} - rlocation key of the extracted sysroot TreeArtifact
#   {{SYSROOT_BINARY}}     - sysroot-absolute path of the ELF binary to run
#   {{EXCLUDE_PATHS}}      - colon-separated FAKECHROOT_EXCLUDE_PATH entries (may be empty)
set -eu

# --- begin POSIX sh runfiles init ---
if [ ! -d "${RUNFILES_DIR:-/dev/null}" ] && [ ! -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]; then
  if [ -f "$0.runfiles_manifest" ]; then
    RUNFILES_MANIFEST_FILE="$0.runfiles_manifest"; export RUNFILES_MANIFEST_FILE
  elif [ -f "$0.runfiles/MANIFEST" ]; then
    RUNFILES_MANIFEST_FILE="$0.runfiles/MANIFEST"; export RUNFILES_MANIFEST_FILE
  elif [ -d "$0.runfiles" ]; then
    RUNFILES_DIR="$0.runfiles"; export RUNFILES_DIR
  else
    echo >&2 "ERROR: cannot find runfiles"
    exit 1
  fi
fi
rlocation() {
  if [ -n "${RUNFILES_DIR:-}" ] && [ -e "${RUNFILES_DIR}/$1" ]; then
    printf '%s' "${RUNFILES_DIR}/$1"
  elif [ -n "${RUNFILES_MANIFEST_FILE:-}" ]; then
    grep -m1 "^$1 " "${RUNFILES_MANIFEST_FILE}" | cut -d' ' -f2-
  fi
}
# --- end POSIX sh runfiles init ---

FAKECHROOT_WRAPPER="$(rlocation '{{WRAPPER_SHORT_PATH}}')"
SYSROOT_DIR="$(rlocation '{{SYSROOT_SHORT_PATH}}')"

if [ -z "${FAKECHROOT_WRAPPER}" ] || [ ! -x "${FAKECHROOT_WRAPPER}" ]; then
  echo "ERROR: could not resolve fakechroot wrapper: {{WRAPPER_SHORT_PATH}}" >&2
  exit 1
fi

if [ -z "${SYSROOT_DIR}" ] || [ ! -d "${SYSROOT_DIR}" ]; then
  echo "ERROR: could not resolve sysroot directory: {{SYSROOT_SHORT_PATH}}" >&2
  exit 1
fi

export SYSROOT_DIR
if [ -n "{{EXCLUDE_PATHS}}" ]; then
  export FAKECHROOT_EXCLUDE_PATH="{{EXCLUDE_PATHS}}"
fi

exec "${FAKECHROOT_WRAPPER}" "{{SYSROOT_BINARY}}" "$@"
