' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml
left to right direction
rectangle "public_api.puml" as arch
rectangle "failuremodes.trlc" as fm
rectangle "controlmeasures.trlc" as cm
rectangle "fta.puml" as fta
rectangle "architecture.lobster" as arch_lob
rectangle "failuremodes.lobster" as fm_lob
rectangle "controlmeasures.lobster" as cm_lob
rectangle "root_causes.lobster" as rc_lob
rectangle "lobster_sa.conf" as conf
rectangle "report.json" as json
rectangle "report.html" as html

arch --> arch_lob : puml_parser
fm --> fm_lob : lobster-trlc
cm --> cm_lob : lobster-trlc
fta --> rc_lob : safety_analysis_tools
arch_lob --> conf
fm_lob --> conf
cm_lob --> conf
rc_lob --> conf
conf --> json : lobster-ci-report
json --> html : lobster-html-report
@enduml
