' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml official_lost_found_endpoint_variants

participant Actor1
participant Actor2
participant Builder

[o-> Actor1 : Incoming request
[-> Actor2 : Another incoming
[x-> Builder : Third incoming
Actor1 -->o] : Outgoing response
Actor2 -->] : Another outgoing
Actor2 -->x] : Third outgoing

@enduml
