' Copyright (c) 2026 Contributors to the Eclipse Foundation
' SPDX-License-Identifier: Apache-2.0

@startuml

class Base

struct Owned
struct Borrowed
struct Result
struct Context

struct Worker

Base <|-- Worker
Owned *-- Worker
Borrowed o-- Worker
Worker --> Result
Worker ..> Context

@enduml
