# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""
Safety Element out of Context (SEooC) build rules for S-CORE projects.

This module provides macros and rules for building SEooC documentation modules
following S-CORE process guidelines. A SEooC is a safety-related element developed
independently of a specific vehicle project.
"""

load("//bazel/rules/score_module/private:providers.bzl", "SphinxSourcesInfo")
load("//bazel/rules/score_module/private:sphinx_module.bzl", "sphinx_module")

# ============================================================================
# Private Rule Implementation
# ============================================================================

def _get_sphinx_files(target):
    """Extract documentation files from a target.

    Handles both targets with SphinxSourcesInfo provider and raw file targets.

    Args:
        target: A Bazel target that may provide SphinxSourcesInfo or raw files

    Returns:
        List of files suitable for Sphinx documentation
    """
    if SphinxSourcesInfo in target:
        return target[SphinxSourcesInfo].srcs.to_list()
    return target.files.to_list()

def _filter_doc_files(files):
    """Filter files to only include documentation files (.rst, .md).

    Args:
        files: List of files to filter

    Returns:
        List of documentation files
    """
    return [f for f in files if f.extension in ["rst", "md"]]

def _software_component_index_impl(ctx):
    """Generate index.rst file with references to all SEooC artifacts.

    This rule creates a Sphinx index.rst file that includes references to all
    the SEooC documentation artifacts (assumptions of use, requirements, design,
    and safety analysis).

    Args:
        ctx: Rule context

    Returns:
        DefaultInfo provider with generated index.rst file
    """

    # Declare output index.rst file
    index_rst = ctx.actions.declare_file(ctx.label.name + "/index.rst")

    # Collect all artifact files and create symlinks
    output_files = [index_rst]
    artifacts_by_type = {
        "assumptions_of_use": [],
        "component_requirements": [],
        "architectural_design": [],
        "dependability_analysis": [],
        "checklists": [],
    }

    # Process each artifact type
    for artifact_name in artifacts_by_type:
        attr_list = getattr(ctx.attr, artifact_name)
        if attr_list:
            # For label_list attributes, iterate over each label
            for label in attr_list:
                # Get files from SphinxSourcesInfo if available, otherwise use raw files
                all_files = _get_sphinx_files(label)

                # Filter to only include documentation files for the index
                doc_files = _filter_doc_files(all_files)

                for artifact_file in doc_files:
                    # Check that artifact is not named index.rst
                    if artifact_file.basename == "index.rst":
                        fail("Error in {}: Artifact file '{}' in '{}' cannot be named 'index.rst' as this file is generated by the SEooC rule and would be overwritten.".format(
                            ctx.label,
                            artifact_file.path,
                            artifact_name,
                        ))

                    # Create symlink in same directory as index
                    output_file = ctx.actions.declare_file(
                        ctx.label.name + "/" + artifact_file.basename,
                    )
                    output_files.append(output_file)

                    # Symlink instead of copying for better performance
                    ctx.actions.symlink(
                        output = output_file,
                        target_file = artifact_file,
                    )

                    # Add reference to index (without file extension)
                    doc_ref = artifact_file.basename.replace(".rst", "").replace(".md", "")
                    artifacts_by_type[artifact_name].append(doc_ref)

    # Substitute template variables (template handles indentation)
    title = ctx.attr.module_name
    underline = "=" * len(title)

    ctx.actions.expand_template(
        template = ctx.file.template,
        output = index_rst,
        substitutions = {
            "{title}": title,
            "{underline}": underline,
            "{description}": ctx.attr.description,
            "{assumptions_of_use}": "\n   ".join(artifacts_by_type["assumptions_of_use"]),
            "{component_requirements}": "\n   ".join(artifacts_by_type["component_requirements"]),
            "{architectural_design}": "\n   ".join(artifacts_by_type["architectural_design"]),
            "{dependability_analysis}": "\n   ".join(artifacts_by_type["dependability_analysis"]),
            "{checklists}": "\n   ".join(artifacts_by_type["checklists"]),
        },
    )

    return [
        DefaultInfo(files = depset(output_files)),
    ]

# ============================================================================
# Private Rule Definition
# ============================================================================

_software_component_index = rule(
    implementation = _software_component_index_impl,
    doc = "Generates index.rst file with references to SEooC artifacts",
    attrs = {
        "module_name": attr.string(
            mandatory = True,
            doc = "Name of the SEooC module (used as document title)",
        ),
        "description": attr.string(
            mandatory = True,
            doc = "Description of the SEooC component that appears at the beginning of the documentation. Supports RST formatting.",
        ),
        "assumptions_of_use": attr.label_list(
            mandatory = True,
            doc = "Assumptions of Use targets or files as defined in the S-CORE process. Can be assumptions_of_use targets or raw .rst/.md files.",
        ),
        "component_requirements": attr.label_list(
            mandatory = True,
            doc = "Component requirements targets or files as defined in the S-CORE process. Can be component_requirements targets or raw .rst/.md files.",
        ),
        "architectural_design": attr.label_list(
            mandatory = True,
            doc = "Architectural design targets or files as defined in the S-CORE process. Can be architectural_design targets or raw .rst/.md files.",
        ),
        "dependability_analysis": attr.label_list(
            mandatory = True,
            doc = "Dependability analysis targets or files as defined in the S-CORE process. Can be dependability_analysis targets or raw .rst/.md files.",
        ),
        "checklists": attr.label_list(
            mandatory = True,
            doc = "Safety checklists targets or files as defined in the S-CORE process.",
        ),
        "template": attr.label(
            allow_single_file = [".rst"],
            mandatory = True,
            doc = "Template file for generating index.rst",
        ),
    },
)

# ============================================================================
# Public Macro
# ============================================================================

def score_component(
        name,
        assumptions_of_use,
        component_requirements,
        architectural_design,
        dependability_analysis,
        description,
        checklists = [],
        implementations = [],
        tests = [],
        deps = [],
        sphinx = "//bazel/rules/score_module:score_build",
        visibility = None):
    """Define a Safety Element out of Context (SEooC) following S-CORE process guidelines.

    This macro creates a complete SEooC module with integrated documentation
    generation. It generates an index.rst file referencing all SEooC artifacts
    and builds HTML documentation using the sphinx_module infrastructure.

    A SEooC is a safety-related architectural element (e.g., a software component)
    that is developed independently of a specific vehicle project and can be
    integrated into different vehicle platforms.

    Args:
        name: The name of the safety element module. Used as the base name for
            all generated targets.
        assumptions_of_use: List of labels to assumptions_of_use targets or raw
            .rst/.md files containing the Assumptions of Use, which define the
            safety-relevant operating conditions and constraints for the SEooC
            as defined in the S-CORE process.
        component_requirements: List of labels to component_requirements targets
            or raw .rst/.md files containing the component requirements specification,
            defining functional and safety requirements as defined in the S-CORE process.
        architectural_design: List of labels to architectural_design targets or raw
            .rst/.md files containing the architectural design specification, describing
            the software architecture and design decisions as defined in the S-CORE process.
        dependability_analysis: List of labels to dependability_analysis targets or raw
            .rst/.md files containing the safety analysis, including FMEA, FMEDA, FTA,
            or other safety analysis results as defined in the S-CORE process.
        description: String containing a high-level description of the SEooC
            component. This text appears at the beginning of the generated documentation,
            providing context about what the component does and its purpose.
            Supports RST formatting.
        checklists: Optional list of labels to .rst or .md files containing
            safety checklists and verification documents as defined in the
            S-CORE process.
        implementations: Optional list of labels to Bazel targets representing
            the actual software implementation (cc_library, cc_binary, etc.)
            that realizes the component requirements. This is the source code
            that implements the safety functions as defined in the S-CORE process.
        tests: Optional list of labels to Bazel test targets (cc_test, py_test, etc.)
            that verify the implementation against requirements. Includes unit
            tests and integration tests as defined in the S-CORE process.
        deps: Optional list of other sphinx_module or SEooC targets this module
            depends on. Cross-references will work automatically.
        sphinx: Label to sphinx build binary. Default: //bazel/rules/score_module:score_build
        visibility: Bazel visibility specification for the generated SEooC targets.

    Generated Targets:
        <name>_seooc_index: Internal rule that generates index.rst and copies artifacts
        <name>: Main SEooC target (sphinx_module) with HTML documentation
        <name>_needs: Internal target for sphinx-needs JSON generation
    """

    # Step 1: Generate index.rst and collect all artifacts
    _software_component_index(
        name = name + "_seooc_index",
        module_name = name,
        description = description,
        template = Label("//bazel/rules/score_module:templates/seooc_index.template.rst"),
        assumptions_of_use = assumptions_of_use,
        component_requirements = component_requirements,
        architectural_design = architectural_design,
        dependability_analysis = dependability_analysis,
        checklists = checklists,
        visibility = ["//visibility:private"],
    )

    # Step 2: Create sphinx_module using generated index and artifacts
    # The index file is part of the _seooc_index target outputs
    sphinx_module(
        name = name,
        srcs = [":" + name + "_seooc_index"],
        index = ":" + name + "_seooc_index",  # Label to the target, not a path
        deps = deps,
        sphinx = sphinx,
        visibility = visibility,
    )
