name: Run Python Basics Integration Tests (Legacy)
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'python_basics/**'
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.0
        with:
          bazelisk-cache: true
          disk-cache: true
          repository-cache: true

      - name: Run integration tests
        run: |
          cd python_basics/integration_tests
          bazel test ...
